#! /usr/bin/python
# -*- coding: utf-8 -*-

import sys

class Humor(object):
    def __init__(self):
        """
        lexicon must be defined:
        that is a dictionary, each key is the wordform,
        corresponding values are stored in a list of tuples.

        e.g: lexicon = { u"utána": [(u"utána", u"[KOT]")] }
        """
        self.lexicon = {u"12.": [(u"12.", u"[MN][NOM]"), (u"12", u"[SZN|DIGIT][NOM]")],
                        u"14.": [(u"14", u"[SZN|DIGIT][NOM]"), (u"14.", u"[MN][NOM]")],
                        u"15-20": [(u"15-20", u"[SZN|DIGIT][NOM]")],
                        u"1827-ben": [(u"1827", u"[SZN|DIGIT][INE]")],
                        u"1960-ban": [(u"1960", u"[SZN|DIGIT][INE]")],
                        u"1983-ban": [(u"1983", u"[SZN|DIGIT][INE]")],
                        u"3-4.": [(u"3-4.", u"[MN][NOM]")],
                        u"3-4": [(u"3-4", u"[SZN|DIGIT][NOM]")],
                        u"40-50": [(u"40-50", u"[SZN|DIGIT][NOM]")],
                        u"500-600": [(u"500-600", u"[SZN|DIGIT][NOM]")],
                        u"5-6": [(u"5-6", u"[SZN|DIGIT][NOM]")],
                        u"5-8": [(u"5-8", u"[SZN|DIGIT][NOM]")],
                        u"80": [(u"80", u"[SZN|DIGIT][NOM]")],
                        u"Abel-díjas": [(u"Abel-díjas", u"[MN][NOM]"), (u"Abel-díjas", u"[FN][NOM]")],
                        u"adott": [(u"adott", u"[MN][NOM]"), (u"ad", u"[IGE][_MIB][NOM]"), (u"ad", u"[IGE][Me3]")],
                        u"adriai": [(u"adriai", u"[MN][NOM]")],
                        u"ad": [(u"ad", u"[IGE][e3]"), (u"ad", u"[X]")],
                        u"Afrika": [(u"Afrika", u"[FN][NOM]")],
                        u"ágai": [(u"ág", u"[FN][PSe3i][NOM]")],
                        u"ágakat": [(u"ág", u"[FN][PL][ACC]")],
                        u"ágak": [(u"ág", u"[FN][PL][NOM]")],
                        u"aggódnak": [(u"aggódik", u"[IGE][t3]"), (u"agg", u"[IGE][_OKEP][PSe2][DAT]")],
                        u"ahhoz": [(u"az", u"[FN|NM][ALL]"), (u"az", u"[DET|NM][ALL]")],
                        u"ahol": [(u"ahol", u"[HA|NM]")],
                        u"akárcsak": [(u"akárcsak", u"[KOT]")],
                        u"akarják": [(u"akar", u"[IGE][Tt3]"), (u"akar", u"[IGE][TPt3]")],
                        u"akkori": [(u"akkori", u"[MN][NOM]"), (u"akkori", u"[MN|NM][NOM]")],
                        u"akkor": [(u"az", u"[FN|NM][TEM]"), (u"az", u"[DET|NM][TEM]"), (u"akkor", u"[HA|NM]")],
                        u"alakítjuk": [(u"alakít", u"[IGE][Tt1]")],
                        u"alaposan": [(u"alapos", u"[MN][_ESSMOD]")],
                        u"alapvető": [(u"alapvető", u"[MN][NOM]"), (u"alapvető", u"[FN][NOM]")],
                        u"alá": [(u"alá", u"[NU][e3]"), (u"alá", u"[IK]"), (u"alá", u"[NU]")],
                        u"alig": [(u"alig", u"[HA]")],
                        u"alkalmasak": [(u"alkalmas", u"[MN][PL][NOM]")],
                        u"alkalmasnak": [(u"alkalmas", u"[FN][DAT]"), (u"alkalmas", u"[MN][DAT]")],
                        u"alkalmával": [(u"alkalom", u"[FN][PSe3][INS]")],
                        u"alkut": [(u"alku", u"[FN][ACC]")],
                        u"állam": [(u"állam", u"[FN][NOM]"), (u"áll", u"[FN][PSe1][NOM]")],
                        u"állnak": [(u"áll", u"[IGE][t3]"), (u"áll", u"[FN][DAT]")],
                        u"álló": [(u"álló", u"[MN][NOM]"), (u"álló", u"[FN][NOM]"), (u"áll", u"[IGE][_OKEP][NOM]")],
                        u"áll": [(u"áll", u"[IGE][e3]"), (u"áll", u"[FN][NOM]")],
                        u"alsóbbrendű": [(u"alsóbbrendű", u"[MN][NOM]")],
                        u"amely": [(u"amely", u"[DET|NM]")],
                        u"amikor": [(u"amikor", u"[HA|NM]"), (u"amikor", u"[KOT]")],
                        u"ami": [(u"ami", u"[DET|NM]")],
                        u"angol": [(u"angol", u"[MN][NOM]")],
                        u"Anjouk": [(u"Anjou", u"[FN][PL][NOM]")],
                        u"Annál": [(u"az", u"[FN|NM][ADE]"), (u"annál", u"[HA]"), (u"az", u"[DET|NM][ADE]")],
                        u"annyira": [(u"annyi", u"[SZN|NM][SUB]"), (u"annyira", u"[HA|NM]")],
                        u"aprók": [(u"apró", u"[MN][PL][NOM]"), (u"apró", u"[FN][PL][NOM]")],
                        u"apró": [(u"apró", u"[MN][NOM]"), (u"apró", u"[FN][NOM]")],
                        u"áramellátási": [(u"áramellátási", u"[MN][NOM]")],
                        u"áramszolgáltatás": [(u"áramszolgáltatás", u"[FN][NOM]")],
                        u"Áramszolgáltató": [(u"áramszolgáltató", u"[MN][NOM]"), (u"áramszolgáltató", u"[FN][NOM]")],
                        u"áram-": [(u"ár", u"[FN][PSe1][NOM]"), (u"áram", u"[FN][NOM]")],
                        u"arasznyi": [(u"arasznyi", u"[MN][NOM]")],
                        u"Aréna": [(u"aréna", u"[FN][NOM]")],
                        u"árnyékában": [(u"árnyék", u"[FN][PSe3][INE]")],
                        u"Árpád": [(u"árpa", u"[FN][PSe2][NOM]"), (u"Árpád", u"[FN][NOM]")],
                        u"arra": [(u"az", u"[FN|NM][SUB]"), (u"az", u"[DET|NM][SUB]")],
                        u"aszalásra": [(u"aszalás", u"[FN][SUB]")],
                        u"aszalják": [(u"aszal", u"[IGE][Tt3]"), (u"aszal", u"[IGE][TPt3]")],
                        u"átmérőjű": [(u"átmérőjű", u"[MN][NOM]")],
                        u"áttelelt": [(u"áttelel", u"[IGE][Me3]"), (u"áttelel", u"[IGE][_MIB][NOM]")],
                        u"a": [(u"a", u"[FN][NOM]"), (u"a", u"[DET]"), (u"a", u"[DET|NM]")],
                        u"A": [(u"a", u"[FN][NOM]"), (u"a", u"[DET]"), (u"a", u"[DET|NM]"), (u"A", u"[FN][NOM]")],
                        u"augusztusra": [(u"augusztus", u"[FN][SUB]")],
                        u"azért": [(u"az", u"[FN|NM][CAU]"), (u"azért", u"[HA|NM]"), (u"az", u"[DET|NM][CAU]")],
                        u"azonban": [(u"azonban", u"[KOT]")],
                        u"aztán": [(u"aztán", u"[HA|NM]")],
                        u"azt": [(u"az", u"[DET|NM][ACC]"), (u"az", u"[FN|NM][ACC]")],
                        u"az": [(u"az", u"[DET|NM][NOM]"), (u"az", u"[DET]"), (u"az", u"[FN|NM][NOM]")],
                        u"Az": [(u"az", u"[DET|NM][NOM]"), (u"az", u"[DET]"), (u"az", u"[FN|NM][NOM]")],
                        u"azután": [(u"azután", u"[HA|NM]"), (u"azután", u"[HA]")],
                        u"Badacsony": [(u"Badacsony", u"[FN][NOM]")],
                        u"Bakondi": [(u"Bakondi", u"[FN][NOM]")],
                        u"baktériumok": [(u"baktérium", u"[FN][PL][NOM]")],
                        u"bankoknál,": [(u"bank", u"[FN][PL][ADE]")],
                        u"bankok": [(u"bank", u"[FN][PL][NOM]")],
                        u"bankválság": [(u"bankválság", u"[FN][NOM]")],
                        u"barnás": [(u"barnás", u"[FN][NOM]"), (u"barnás", u"[MN][NOM]")],
                        u"Bár": [(u"bár", u"[KOT]"), (u"Bár", u"[FN][NOM]"), (u"bár", u"[FN][NOM]")],
                        u"Becket": [(u"Beck", u"[FN][ACC]")],
                        u"beérik": [(u"beér", u"[IGE][Tt3]"), (u"beérik", u"[IGE][Tt3]"), (u"beérik", u"[IGE][e3]")],
                        u"beérnek": [(u"beérik", u"[IGE][t3]"), (u"beér", u"[IGE][t3]")],
                        u"befőtt": [(u"befő", u"[IGE][_MIB][NOM]"), (u"befőtt", u"[FN][NOM]"), (u"befő", u"[IGE][Me3]")],
                        u"bejelentette": [(u"bejelentet", u"[IGE][_MIB_SUBJ=tA][NOM]"), (u"bejelentet", u"[IGE][_IF=tA][PSe3][NOM]"), (u"bejelent", u"[IGE][_MIB_SUBJ=tA][NOM]"), (u"bejelent", u"[IGE][_IF=tA][PSe3][NOM]"), (u"bejelent", u"[IGE][TMe3]"), (u"bejelentet", u"[IGE][TMe3]")],
                        u"belőle": [(u"ő", u"[FN|NM][ELA][e3]")],
                        u"belül": [(u"belül", u"[NU]"), (u"belül", u"[HA]")],
                        u"betakarítani": [(u"betakarít", u"[IGE][INF]")],
                        u"betegsége": [(u"betegség", u"[FN][PSe3][NOM]")],
                        u"be": [(u"be", u"[IK]")],
                        u"Bevetik": [(u"bevet", u"[IGE][Tt3]")],
                        u"bimbóhoz": [(u"bimbó", u"[FN][ALL]")],
                        u"bírálja": [(u"bírál", u"[IGE][TPe3]"), (u"bírál", u"[IGE][Te3]")],
                        u"bizony": [(u"bizony", u"[HA]")],
                        u"biztosnak": [(u"biztos", u"[FN][DAT]"), (u"biztos", u"[MN][DAT]")],
                        u"biztos": [(u"biztos", u"[FN][NOM]"), (u"biztos", u"[MN][NOM]")],
                        u"blogírók": [(u"blogíró", u"[MN][PL][NOM]"), (u"blogíró", u"[FN][PL][NOM]")],
                        u"blog": [(u"blog", u"[FN][NOM]")],
                        u"blokád": [(u"blokád", u"[FN][NOM]")],
                        u"Blokád": [(u"blokád", u"[FN][NOM]")],
                        u"Bodeni-tóban": [(u"Bodeni-tó", u"[FN][INE]")],
                        u"bokorról": [(u"bokor", u"[FN][DEL]")],
                        u"bokrokat": [(u"bokor", u"[FN][PL][ACC]")],
                        u"bokroknál": [(u"bokor", u"[FN][PL][ADE]")],
                        u"bokrokról": [(u"bokor", u"[FN][PL][DEL]")],
                        u"bokrot": [(u"bokor", u"[FN][ACC]")],
                        u"bort": [(u"bor", u"[FN][ACC]")],
                        u"bor": [(u"bor", u"[FN][NOM]")],
                        u"Bölcsészettudományi": [(u"bölcsészettudományi", u"[MN][NOM]")],
                        u"bőséges": [(u"bőséges", u"[FN][NOM]"), (u"bőséges", u"[MN][NOM]")],
                        u"brit": [(u"brit", u"[MN][NOM]")],
                        u"(BTK)": [(u"BTK", u"[FN][NOM]")],
                        u"Buda-vidék": [(u"Buda-vidék", u"[FN][NOM]")],
                        u"cég": [(u"cég", u"[FN][NOM]")],
                        u"című": [(u"című", u"[MN][NOM]")],
                        u"Cipruson": [(u"Ciprus", u"[FN][SUP]"), (u"ciprus", u"[FN][SUP]")],
                        u"cm": [(u"cm", u"[FN][NOM]")],
                        u"°C-nál": [(u"°C", u"[FN][ADE]")],
                        u"°C-on": [(u"°C", u"[FN][SUP]")],
                        u"cukrozott": [(u"cukrozik", u"[IGE][Me3]"), (u"cukroz", u"[IGE][Me3]"), (u"cukrozott", u"[MN][NOM]"), (u"cukroz", u"[IGE][_MIB][NOM]"), (u"cukrozik", u"[IGE][_MIB][NOM]")],
                        u"csak": [(u"csak", u"[HA]")],
                        u"családból": [(u"család", u"[FN][ELA]")],
                        u"csatorna-": [(u"csatorna", u"[FN][NOM]")],
                        u"csemetéket": [(u"csemete", u"[FN][PL][ACC]")],
                        u"csemetét": [(u"csemete", u"[FN][ACC]")],
                        u"cseréjéhez": [(u"csere", u"[FN][PSe3][ALL]")],
                        u"cseréjét": [(u"csere", u"[FN][PSe3][ACC]")],
                        u"csökkentéséről": [(u"csökkentés", u"[FN][PSe3][DEL]"), (u"csökkentés", u"[FN][POS][DEL]")],
                        u"csütörtökön": [(u"csütörtök", u"[FN][SUP]")],
                        u"csütörtök": [(u"csütörtök", u"[FN][NOM]")],
                        u"dékán": [(u"dékán", u"[FN][NOM]")],
                        u"délben": [(u"dél", u"[FN][INE]")],
                        u"Dél-Bulgáriában": [(u"dél-Bulgária", u"[FN][INE]")],
                        u"Dél-Európában": [(u"dél-Európa", u"[FN][INE]")],
                        u"déli": [(u"déli", u"[MN][NOM]")],
                        u"dél-koreai": [(u"dél-koreai", u"[MN][NOM]")],
                        u"délre": [(u"dél", u"[FN][SUB]")],
                        u"derül": [(u"derül", u"[IGE][e3]")],
                        u"de": [(u"de", u"[HA]"), (u"de", u"[X]"), (u"de", u"[KOT]")],
                        u"Dezső": [(u"Dezső", u"[FN][NOM]"), (u"dezső", u"[FN][NOM]")],
                        u"díjak": [(u"díj", u"[FN][PL][NOM]")],
                        u"diónyi": [(u"diónyi", u"[MN][NOM]")],
                        u"dokumentum": [(u"dokumentum", u"[FN][NOM]")],
                        u"döntését": [(u"döntés", u"[FN][PSe3][ACC]"), (u"döntés", u"[FN][POS][ACC]")],
                        u"Dr.": [(u"dr.", u"[FN][NOM]")],
                        u"ebben": [(u"ez", u"[DET|NM][INE]"), (u"eb", u"[FN][INE]"), (u"ez", u"[FN|NM][INE]")],
                        u"édes": [(u"édes", u"[MN][NOM]"), (u"édes", u"[FN][NOM]")],
                        u"egészséges": [(u"egészséges", u"[MN][NOM]"), (u"egészséges", u"[FN][NOM]")],
                        u"egyébként": [(u"egyébként", u"[HA]"), (u"egyéb", u"[FN|NM][FOR]"), (u"egyéb", u"[MN|NM][FOR]")],
                        u"egyelőre": [(u"egyel", u"[IGE][_OKEP][SUB]"), (u"egyelőre", u"[HA]")],
                        u"egyértelműsíteni": [(u"egyértelműsít", u"[IGE][INF]")],
                        u"egyetemen": [(u"egyetem", u"[FN][SUP]")],
                        u"egyidejűleg": [(u"egyidejűleg", u"[HA]")],
                        u"Egyike": [(u"egyik", u"[MN|NM][PSe3][NOM]")],
                        u"egyszerű": [(u"egyszerű", u"[MN][NOM]")],
                        u"egy": [(u"egy", u"[SZN][NOM]"), (u"egy", u"[FN|NM][NOM]"), (u"egy", u"[DET]")],
                        u"Egy": [(u"egy", u"[SZN][NOM]"), (u"egy", u"[FN|NM][NOM]"), (u"egy", u"[DET]")],
                        u"ekkor": [(u"ez", u"[DET|NM][TEM]"), (u"ekkor", u"[HA|NM]"), (u"ez", u"[FN|NM][TEM]")],
                        u"Ekkor": [(u"ez", u"[DET|NM][TEM]"), (u"ekkor", u"[HA|NM]"), (u"ez", u"[FN|NM][TEM]")],
                        u"éles": [(u"éles", u"[MN][NOM]"), (u"éles", u"[FN][NOM]")],
                        u"életmódjának": [(u"életmód", u"[FN][PSe3][DAT]")],
                        u"elé": [(u"elé", u"[NU]"), (u"elé", u"[NU][e3]")],
                        u"elfér": [(u"elfér", u"[IGE][e3]")],
                        u"elfödésére": [(u"elfödés", u"[FN][PSe3][SUB]"), (u"elfödés", u"[FN][POS][SUB]")],
                        u"eljuttatott": [(u"eljuttat", u"[IGE][Me3]"), (u"eljuttat", u"[IGE][_MIB][NOM]")],
                        u"elkerülése": [(u"elkerülés", u"[FN][PSe3][NOM]")],
                        u"ellenálló": [(u"ellenálló", u"[MN][NOM]"), (u"ellenálló", u"[FN][NOM]"), (u"ellenáll", u"[IGE][_OKEP][NOM]")],
                        u"elmondta": [(u"elmond", u"[IGE][_MIB_SUBJ=tA][NOM]"), (u"elmond", u"[IGE][_IF=tA][PSe3][NOM]"), (u"elmond", u"[IGE][TMe3]")],
                        u"elmúltával": [(u"elmúlta", u"[FN][PSe3][INS]"), (u"elmúlik", u"[IGE][_MIB_SUBJ=tA][INS]"), (u"elmúl", u"[IGE][_MIB_SUBJ=tA][INS]"), (u"elmúlik", u"[IGE][_IF=tA][PSe3][INS]"), (u"elmúlt", u"[MN][PSe3][INS]"), (u"elmúl", u"[IGE][_IF=tA][PSe3][INS]")],
                        u"elnöke": [(u"elnök", u"[FN][PSe3][NOM]")],
                        u"előfordul": [(u"előfordul", u"[IGE][e3]")],
                        u"előrejelzéséből": [(u"előrejelzés", u"[FN][PSe3][ELA]"), (u"előrejelzés", u"[FN][POS][ELA]")],
                        u"elő": [(u"elő", u"[IK]")],
                        u"előző": [(u"előz", u"[IGE][_OKEP][NOM]"), (u"előző", u"[MN][NOM]")],
                        u"elpusztíthatatlanok": [(u"elpusztíthatatlan", u"[MN][PL][NOM]")],
                        u"első": [(u"első", u"[MN][NOM]")],
                        u"eltartani": [(u"eltart", u"[IGE][INF]")],
                        u"eltérően": [(u"eltérő", u"[MN][_ESSMOD]")],
                        u"(ELTE)": [(u"ELTE", u"[FN][NOM]")],
                        u"ELTE": [(u"ELTE", u"[FN][NOM]")],
                        u"eltiltott": [(u"eltilt", u"[IGE][_MIB][NOM]"), (u"eltilt", u"[IGE][Me3]")],
                        u"élt": [(u"él", u"[FN][ACC]"), (u"él", u"[IGE][_MIB][NOM]"), (u"él", u"[IGE][Me3]")],
                        u"el": [(u"el", u"[IK]")],
                        u"élvezheti": [(u"élvez", u"[IGE][_HAT][Te3]")],
                        u"élvezhető": [(u"élvezhető", u"[MN][NOM]")],
                        u"elzárt": [(u"elzár", u"[IGE][Me3]"), (u"elzár", u"[IGE][_MIB][NOM]")],
                        u"Endre": [(u"Endre", u"[FN][NOM]"), (u"end", u"[FN][SUB]")],
                        u"ennek": [(u"ez", u"[DET|NM][DAT]"), (u"ez", u"[FN|NM][DAT]")],
                        u"enyhül": [(u"enyh", u"[FN][ESS]"), (u"enyhül", u"[IGE][e3]")],
                        u"Eötvös": [(u"Eötvös", u"[FN][NOM]")],
                        u"eperfának": [(u"eperfa", u"[FN][DAT]")],
                        u"építkezés": [(u"építkezés", u"[FN][NOM]")],
                        u"érdekében": [(u"érdek", u"[FN][POS][INE]"), (u"érdek", u"[FN][PSe3][INE]"), (u"érdekében", u"[NU][e3]")],
                        u"eredeti": [(u"eredeti", u"[MN][NOM]")],
                        u"eredményes": [(u"eredményes", u"[FN][NOM]"), (u"eredményes", u"[MN][NOM]")],
                        u"erednek": [(u"ér", u"[FN][PSe2][DAT]"), (u"ered", u"[IGE][t3]")],
                        u"ered": [(u"ered", u"[IGE][e3]"), (u"ér", u"[FN][PSe2][NOM]")],
                        u"érésű": [(u"érésű", u"[MN][NOM]")],
                        u"ereszt": [(u"eresz", u"[FN][ACC]"), (u"ereszt", u"[IGE][e3]")],
                        u"éretlen": [(u"éretlen", u"[MN][NOM]"), (u"éretlen", u"[MN][_ESSMOD=0]")],
                        u"éretlenül": [(u"éretlen", u"[MN][_ESSMOD]")],
                        u"éretten": [(u"érik", u"[IGE][_MIB][_ESSMOD]"), (u"éret", u"[IGE][_HIN=ttOn]"), (u"érett", u"[MN][_ESSMOD]"), (u"érik", u"[IGE][_MIB][SUP]"), (u"érett", u"[MN][SUP]")],
                        u"érett": [(u"érik", u"[IGE][_MIB][NOM]"), (u"érett", u"[MN][NOM]"), (u"érik", u"[IGE][Me3]")],
                        u"érik": [(u"érik", u"[IGE][Tt3]"), (u"ér", u"[IGE][Tt3]"), (u"érik", u"[IGE][e3]")],
                        u"éri": [(u"érik", u"[IGE][Te3]"), (u"ér", u"[IGE][Te3]"), (u"éri", u"[MN][NOM]")],
                        u"érlelnek": [(u"érlel", u"[IGE][t3]")],
                        u"érlel": [(u"érlel", u"[IGE][e3]")],
                        u"érnek": [(u"érik", u"[IGE][t3]"), (u"ér", u"[FN][DAT]"), (u"ér", u"[IGE][t3]")],
                        u"Erre": [(u"ez", u"[DET|NM][SUB]"), (u"ez", u"[FN|NM][SUB]")],
                        u"erről": [(u"ez", u"[DET|NM][DEL]"), (u"ez", u"[FN|NM][DEL]")],
                        u"értékesebb": [(u"értékes", u"[MN][_FOK][NOM]")],
                        u"értékes": [(u"értékes", u"[MN][NOM]"), (u"értékes", u"[FN][NOM]")],
                        u"érvényesítésére": [(u"érvényesítés", u"[FN][POS][SUB]"), (u"érvényesítés", u"[FN][PSe3][SUB]")],
                        u"esetén": [(u"eset", u"[FN][POS][SUP]"), (u"eset", u"[FN][PSe3][SUP]"), (u"esetén", u"[NU]")],
                        u"esik": [(u"esik", u"[IGE][Tt3]"), (u"esik", u"[IGE][e3]")],
                        u"eső": [(u"eső", u"[MN][NOM]"), (u"eső", u"[FN][NOM]"), (u"esik", u"[IGE][_OKEP][NOM]")],
                        u"Esterházy": [(u"Esterházy", u"[FN][NOM]")],
                        u"este": [(u"este", u"[FN][_TMP_INL]"), (u"esik", u"[IGE][_IF=tA][PSe3][NOM]"), (u"este", u"[FN][NOM]"), (u"esik", u"[IGE][_MIB_SUBJ=tA][NOM]"), (u"este", u"[HA]"), (u"esik", u"[IGE][TMe3]")],
                        u"és": [(u"és", u"[KOT]")],
                        u"Észak-Afrikában": [(u"észak-Afrika", u"[FN][INE]")],
                        u"Észak-Korea": [(u"észak-Korea", u"[FN][NOM]"), (u"Észak-Korea", u"[FN][NOM]")],
                        u"Észak-magyarországi": [(u"észak-magyarországi", u"[MN][NOM]")],
                        u"Esztergom": [(u"Esztergom", u"[FN][NOM]")],
                        u"ételosztásba": [(u"ételosztás", u"[FN][ILL]")],
                        u"ételt": [(u"étel", u"[FN][ACC]")],
                        u"Etikai": [(u"etikai", u"[MN][NOM]")],
                        u"európai": [(u"európai", u"[MN][NOM]")],
                        u"évben": [(u"év", u"[FN][INE]")],
                        u"években": [(u"év", u"[FN][PL][INE]")],
                        u"évente": [(u"évente", u"[HA]")],
                        u"éves": [(u"éves", u"[FN][NOM]"), (u"éves", u"[MN][NOM]")],
                        u"év": [(u"év", u"[FN][NOM]")],
                        u"Ezeket": [(u"ez", u"[FN|NM][PL][ACC]"), (u"ez", u"[DET|NM][PL][ACC]")],
                        u"ezek": [(u"ez", u"[DET|NM][PL][NOM]"), (u"ez", u"[FN|NM][PL][NOM]")],
                        u"Ezek": [(u"ez", u"[DET|NM][PL][NOM]"), (u"ez", u"[FN|NM][PL][NOM]")],
                        u"ezért": [(u"ezért", u"[HA|NM]"), (u"ez", u"[DET|NM][CAU]"), (u"ez", u"[FN|NM][CAU]")],
                        u"Ezért": [(u"ezért", u"[HA|NM]"), (u"ez", u"[DET|NM][CAU]"), (u"ez", u"[FN|NM][CAU]")],
                        u"ezt": [(u"ez", u"[FN|NM][ACC]"), (u"ez", u"[DET|NM][ACC]")],
                        u"Ezt": [(u"ez", u"[FN|NM][ACC]"), (u"ez", u"[DET|NM][ACC]")],
                        u"ez": [(u"ez", u"[DET|NM][NOM]"), (u"ez", u"[FN|NM][NOM]")],
                        u"Ez": [(u"ez", u"[DET|NM][NOM]"), (u"ez", u"[FN|NM][NOM]")],
                        u"ezúttal": [(u"ezúttal", u"[HA|NM]")],
                        u"fagyérzékeny": [(u"fagyérzékeny", u"[MN][NOM]")],
                        u"fagyjanak": [(u"fagy", u"[IGE][Pt3]")],
                        u"fagykárokat": [(u"fagykár", u"[FN][PL][ACC]")],
                        u"fagykár": [(u"fagykár", u"[FN][NOM]")],
                        u"fagyok": [(u"fagy", u"[FN][PL][NOM]"), (u"fagy", u"[IGE][e1]")],
                        u"fagy": [(u"fagy", u"[IGE][e3]"), (u"fagy", u"[FN][NOM]")],
                        u"fakadnak": [(u"fakad", u"[IGE][t3]")],
                        u"fákból": [(u"fa", u"[FN][PL][ELA]")],
                        u"falak": [(u"falak", u"[FN][NOM]"), (u"fal", u"[FN][PL][NOM]")],
                        u"falhoz": [(u"fal", u"[FN][ALL]")],
                        u"falombbal": [(u"falomb", u"[FN][INS]")],
                        u"fanyar": [(u"fanyar", u"[MN][NOM]")],
                        u"farkasanya": [(u"farkasanya", u"[FN][NOM]")],
                        u"fáról": [(u"fa", u"[FN][DEL]")],
                        u"Fegyveres": [(u"fegyveres", u"[MN][NOM]"), (u"fegyveres", u"[FN][NOM]")],
                        u"fejlődő": [(u"fejlődik", u"[IGE][_OKEP][NOM]")],
                        u"felelős": [(u"felelős", u"[FN][NOM]"), (u"felelős", u"[MN][NOM]")],
                        u"félérett": [(u"félérett", u"[MN][NOM]")],
                        u"fél-érett": [(u"fél-érik", u"[IGE][Me3]"), (u"fél-érik", u"[IGE][_MIB][NOM]"), (u"fél-érett", u"[MN][NOM]")],
                        u"felett": [(u"felett", u"[NU]")],
                        u"feltéve": [(u"feltéve", u"[HA]"), (u"feltesz", u"[IGE][_HIN]")],
                        u"Féltrópusi": [(u"féltrópusi", u"[MN][NOM]")],
                        u"fel": [(u"fel", u"[IK]")],
                        u"fenyegeti": [(u"fenyeget", u"[IGE][Te3]")],
                        u"fiatal": [(u"fiatal", u"[FN][NOM]"), (u"fiatal", u"[MN][NOM]")],
                        u"figyelmeztetést": [(u"figyelmeztetés", u"[FN][ACC]")],
                        u"fikusznak": [(u"fikusz", u"[FN][DAT]")],
                        u"foglalkozhat": [(u"foglalkozik", u"[IGE][_HAT][e3]")],
                        u"foglalkoztak": [(u"foglalkozik", u"[IGE][Mt3]")],
                        u"fogyasztói": [(u"fogyasztói", u"[MN][NOM]"), (u"fogyasztó", u"[FN][PSe3i][NOM]"), (u"fogyaszt", u"[IGE][_OKEP][PSe3i][NOM]")],
                        u"fokozatosan": [(u"fokozatos", u"[MN][_ESSMOD]")],
                        u"folyamán": [(u"folyam", u"[FN][PSe3][SUP]"), (u"folyamán", u"[NU]")],
                        u"folytatásáról": [(u"folytatásáról", u"[FN][NOM]"), (u"folytatás", u"[FN][PSe3][DEL]")],
                        u"fontos": [(u"fontos", u"[FN][NOM]"), (u"fontos", u"[MN][NOM]")],
                        u"fordul": [(u"fordul", u"[IGE][e3]")],
                        u"forinttal": [(u"forint", u"[FN][INS]")],
                        u"forint": [(u"forint", u"[FN][NOM]")],
                        u"Főigazgatóság": [(u"főigazgatóság", u"[FN][NOM]")],
                        u"földdel": [(u"föld", u"[FN][INS]")],
                        u"földet": [(u"föld", u"[FN][ACC]")],
                        u"földig": [(u"föld", u"[FN][TER]")],
                        u"földjének": [(u"föld", u"[FN][PSe3][DAT]")],
                        u"föld": [(u"föld", u"[FN][NOM]")],
                        u"Fő": [(u"fő", u"[FN][NOM]"), (u"fő", u"[IGE][e3]"), (u"fő", u"[MN][NOM]")],
                        u"főváros": [(u"főváros", u"[FN][NOM]")],
                        u"főznek": [(u"főz", u"[IGE][t3]")],
                        u"Franciaországban": [(u"Franciaország", u"[FN][INE]")],
                        u"fügebokor": [(u"fügebokor", u"[FN][NOM]")],
                        u"fügebokraink": [(u"fügebokor", u"[FN][PSt1i][NOM]")],
                        u"fügebokrokat": [(u"fügebokor", u"[FN][PL][ACC]")],
                        u"fügebokrokkal": [(u"fügebokor", u"[FN][PL][INS]")],
                        u"fügebokrok": [(u"fügebokor", u"[FN][PL][NOM]")],
                        u"fügebokrot": [(u"fügebokor", u"[FN][ACC]")],
                        u"fügéből": [(u"füge", u"[FN][ELA]")],
                        u"fügedarázs": [(u"fügedarázs", u"[FN][NOM]")],
                        u"fügefa": [(u"fügefa", u"[FN][NOM]")],
                        u"fügegyümölcsöt": [(u"fügegyümölcs", u"[FN][ACC]")],
                        u"fügék": [(u"füge", u"[FN][PL][NOM]")],
                        u"fügének": [(u"füge", u"[FN][DAT]")],
                        u"fügenövény": [(u"fügenövény", u"[FN][NOM]")],
                        u"fügét": [(u"füge", u"[FN][ACC]")],
                        u"füge": [(u"füge", u"[FN][NOM]")],
                        u"függetlensége": [(u"függetlenség", u"[FN][PSe3][NOM]")],
                        u"fűzik": [(u"fűz", u"[IGE][Tt3]")],
                        u"fűzött": [(u"fűz", u"[IGE][_MIB][NOM]"), (u"fűzött", u"[MN][NOM]"), (u"fűz", u"[IGE][Me3]")],
                        u"gabona": [(u"gabona", u"[FN][NOM]")],
                        u"gázár": [(u"gázár", u"[FN][NOM]")],
                        u"gazdája": [(u"gazda", u"[FN][PSe3][NOM]")],
                        u"gazdák": [(u"gazda", u"[FN][PL][NOM]")],
                        u"gazdasági": [(u"gazdasági", u"[MN][NOM]")],
                        u"Gellérthegy": [(u"Gellérthegy", u"[FN][NOM]")],
                        u"gondolkodásmód": [(u"gondolkodásmód", u"[FN][NOM]")],
                        u"gumifának": [(u"gumifa", u"[FN][DAT]")],
                        u"gyakran": [(u"gyakori", u"[MN][_ESSMOD]"), (u"gyakran", u"[HA]")],
                        u"Gyakran": [(u"gyakori", u"[MN][_ESSMOD]"), (u"gyakran", u"[HA]")],
                        u"gyógyszereknek": [(u"gyógyszer", u"[FN][PL][DAT]")],
                        u"gyomtalanítást": [(u"gyomtalanítás", u"[FN][ACC]")],
                        u"gyorsabb": [(u"gyors", u"[MN][_FOK][NOM]")],
                        u"gyökeres": [(u"gyökeres", u"[FN][NOM]"), (u"gyökeres", u"[MN][NOM]")],
                        u"György": [(u"György", u"[FN][NOM]")],
                        u"gyümölccsé": [(u"gyümölcs", u"[FN][FAC]")],
                        u"gyümölcseiket": [(u"gyümölcs", u"[FN][PSt3i][ACC]")],
                        u"gyümölcsei": [(u"gyümölcs", u"[FN][PSe3i][NOM]")],
                        u"gyümölcse": [(u"gyümölcs", u"[FN][PSe3][NOM]")],
                        u"gyümölcsfákat": [(u"gyümölcsfa", u"[FN][PL][ACC]")],
                        u"gyümölcskezdemények": [(u"gyümölcskezdemény", u"[FN][PL][NOM]")],
                        u"gyümölcsöket": [(u"gyümölcs", u"[FN][PL][ACC]")],
                        u"gyümölcsök": [(u"gyümölcs", u"[FN][PL][NOM]")],
                        u"gyümölcsöt": [(u"gyümölcs", u"[FN][ACC]")],
                        u"gyümölcs": [(u"gyümölcs", u"[FN][NOM]")],
                        u"hagyjuk": [(u"hagy", u"[IGE][Tt1]"), (u"hagy", u"[IGE][TPt1]")],
                        u"hajnalban": [(u"hajnal", u"[FN][INE]")],
                        u"hajtásból": [(u"hajtás", u"[FN][ELA]"), (u"hajtás", u"[MN][ELA]")],
                        u"hajtásokról": [(u"hajtás", u"[FN][PL][DEL]")],
                        u"hajtást": [(u"hajtás", u"[FN][ACC]")],
                        u"hajtás": [(u"hajtás", u"[FN][NOM]"), (u"hajtás", u"[MN][NOM]")],
                        u"hangon": [(u"hang", u"[FN][SUP]")],
                        u"három": [(u"három", u"[SZN][NOM]")],
                        u"hasonló": [(u"hasonló", u"[FN][NOM]"), (u"hasonló", u"[MN][NOM]"), (u"hasonlik", u"[IGE][_OKEP][NOM]")],
                        u"használják": [(u"használ", u"[IGE][TPt3]"), (u"használ", u"[IGE][Tt3]")],
                        u"határán": [(u"határ", u"[FN][PSe3][SUP]")],
                        u"hat": [(u"hat", u"[SZN][NOM]"), (u"hat", u"[IGE][e3]")],
                        u"ha": [(u"ha", u"[ISZ]"), (u"ha", u"[FN][NOM]"), (u"ha", u"[KOT]")],
                        u"Ha": [(u"ha", u"[ISZ]"), (u"ha", u"[FN][NOM]"), (u"ha", u"[KOT]")],
                        u"havazásra": [(u"havazás", u"[FN][SUB]")],
                        u"hazai": [(u"hazai", u"[MN][NOM]")],
                        u"Hazai": [(u"hazai", u"[MN][NOM]")],
                        u"Hazájában": [(u"haza", u"[FN][PSe3][INE]")],
                        u"hazája": [(u"haza", u"[FN][PSe3][NOM]")],
                        u"Hazánkban": [(u"haza", u"[FN][PSt1][INE]")],
                        u"házikerti": [(u"házikerti", u"[MN][NOM]")],
                        u"Házilagos": [(u"házilagos", u"[MN][NOM]")],
                        u"háztartási": [(u"háztartási", u"[MN][NOM]")],
                        u"Ház": [(u"ház", u"[FN][NOM]")],
                        u"hegy-oldali": [(u"hegy-oldali", u"[MN][NOM]")],
                        u"helyenként": [(u"helyenként", u"[HA]")],
                        u"helyen": [(u"hely", u"[FN][SUP]")],
                        u"helye": [(u"hely", u"[FN][PSe3][NOM]")],
                        u"helyreállítása": [(u"helyreállítás", u"[FN][PSe3][NOM]")],
                        u"helyreállt": [(u"helyreáll", u"[IGE][_MIB][NOM]"), (u"helyreáll", u"[IGE][Me3]")],
                        u"helyre": [(u"helyre", u"[MN][NOM]"), (u"hely", u"[FN][SUB]"), (u"helyre", u"[IK]")],
                        u"Henrik": [(u"Henri", u"[FN][PL][NOM]"), (u"Henrik", u"[FN][NOM]")],
                        u"héten": [(u"hét", u"[SZN][SUP]"), (u"hét", u"[FN][SUP]")],
                        u"hétfőre": [(u"hétfő", u"[FN][SUB]")],
                        u"hétig": [(u"hét", u"[FN][TER]"), (u"hét", u"[SZN][TER]")],
                        u"heti": [(u"heti", u"[MN][NOM]")],
                        u"hiányában": [(u"hiányában", u"[NU]"), (u"hiány", u"[FN][PSe3][INE]")],
                        u"hidegben": [(u"hideg", u"[MN][INE]"), (u"hideg", u"[FN][INE]")],
                        u"hidegebb": [(u"hideg", u"[MN][_FOK][NOM]")],
                        u"hideg": [(u"hideg", u"[MN][NOM]"), (u"hideg", u"[FN][NOM]")],
                        u"higiénia": [(u"higiénia", u"[FN][NOM]")],
                        u"hiszen": [(u"hisz", u"[FN][SUP]"), (u"hiszen", u"[KOT]")],
                        u"hivatalvezetője": [(u"hivatalvezető", u"[MN][PSe3][NOM]"), (u"hivatalvezető", u"[FN][PSe3][NOM]")],
                        u"Hivatásos": [(u"hivatásos", u"[FN][NOM]"), (u"hivatásos", u"[MN][NOM]")],
                        u"(HM)": [(u"HM", u"[FN][NOM]"), (u"hm", u"[ISZ]")],
                        u"hogy": [(u"hogy", u"[KOT]"), (u"ahogy", u"[HA|NM]"), (u"hogy", u"[HA|NM]")],
                        u"homok": [(u"homok", u"[FN][NOM]")],
                        u"Honvédelmi": [(u"honvédelmi", u"[MN][NOM]")],
                        u"hordóba": [(u"hord", u"[IGE][_OKEP][ILL]"), (u"hordó", u"[FN][ILL]")],
                        u"hosszú": [(u"hosszú", u"[MN][NOM]")],
                        u"hozott": [(u"hoz", u"[IGE][Me3]"), (u"hoz", u"[IGE][_MIB][NOM]")],
                        u"hozták": [(u"hoz", u"[IGE][_MIB_SUBJ=tA][PL][NOM]"), (u"hoz", u"[IGE][TMt3]")],
                        u"hozzánk": [(u"mi", u"[FN|NM][ALL][t1]")],
                        u"Hunor": [(u"Hunor", u"[FN][NOM]")],
                        u"hűtőszekrényben": [(u"hűtőszekrény", u"[FN][INE]")],
                        u"Hűvösebb": [(u"hűvös", u"[MN][_FOK][NOM]")],
                        u"idején": [(u"idején", u"[HA]"), (u"idő", u"[FN][PSe3][SUP]")],
                        u"időjárás": [(u"időjárás", u"[FN][NOM]")],
                        u"idők": [(u"idő", u"[FN][PL][NOM]")],
                        u"időpontját": [(u"időpont", u"[FN][PSe3][ACC]")],
                        u"idősebb": [(u"idős", u"[MN][_FOK][NOM]")],
                        u"idő": [(u"idő", u"[FN][NOM]")],
                        u"igazgatóság": [(u"igazgatóság", u"[FN][NOM]")],
                        u"igazságszolgáltatás": [(u"igazságszolgáltatás", u"[FN][NOM]")],
                        u"igazságügyi": [(u"igazságügyi", u"[MN][NOM]")],
                        u"igen": [(u"igen", u"[MSZ]"), (u"igen", u"[FN][NOM]"), (u"igen", u"[HA]")],
                        u"ígéret": [(u"ígéret", u"[FN][NOM]")],
                        u"így": [(u"így", u"[KOT]"), (u"így", u"[HA|NM]")],
                        u"II.": [(u"II", u"[ROMAN][NOM]"), (u"II.", u"[MN][NOM]")],
                        u"illetlen": [(u"illetlen", u"[MN][NOM]"), (u"illetlen", u"[MN][_ESSMOD=0]")],
                        u"illetve": [(u"illet", u"[IGE][_HIN]"), (u"illetve", u"[KOT]")],
                        u"ilyen": [(u"ilyen", u"[MN|NM][NOM]")],
                        u"Imádkoznak": [(u"imádkozik", u"[IGE][t3]")],
                        u"InfoRádió": [(u"InfoRádió", u"[FN][NOM]")],
                        u"inkább": [(u"inkább", u"[HA]"), (u"inka", u"[MN][_FOK][NOM]")],
                        u"írja": [(u"ír", u"[IGE][Te3]"), (u"ír", u"[FN][PSe3][NOM]"), (u"ír", u"[IGE][TPe3]")],
                        u"írta": [(u"ír", u"[IGE][_MIB_SUBJ=tA][NOM]"), (u"ír", u"[IGE][_IF=tA][PSe3][NOM]"), (u"ír", u"[IGE][TMe3]")],
                        u"írt": [(u"ír", u"[IGE][Me3]"), (u"ír", u"[FN][ACC]"), (u"ír", u"[IGE][_MIB][NOM]"), (u"ír", u"[MN][ACC]")],
                        u"iskolai": [(u"iskolai", u"[MN][NOM]")],
                        u"ismerője": [(u"ismer", u"[IGE][_OKEP][PSe3][NOM]")],
                        u"is": [(u"is", u"[HA]")],
                        u"italoktól": [(u"ital", u"[FN][PL][ABL]")],
                        u"ítélik": [(u"ítél", u"[IGE][Tt3]")],
                        u"Izrael": [(u"Izrael", u"[FN][NOM]")],
                        u"ízű": [(u"ízű", u"[MN][NOM]")],
                        u"járható": [(u"járható", u"[MN][NOM]")],
                        u"járókelők": [(u"járókelő", u"[MN][PL][NOM]"), (u"járókelő", u"[FN][PL][NOM]")],
                        u"járvány": [(u"járvány", u"[FN][NOM]")],
                        u"javítását": [(u"javítás", u"[FN][PSe3][ACC]")],
                        u"jelenleg": [(u"jelenleg", u"[HA]")],
                        u"jelentenek": [(u"jelent", u"[IGE][t3]")],
                        u"jelentésében": [(u"jelentés", u"[FN][POS][INE]"), (u"jelentés", u"[FN][PSe3][INE]")],
                        u"jelentette": [(u"jelentet", u"[IGE][_MIB_SUBJ=tA][NOM]"), (u"jelent", u"[IGE][TMe3]"), (u"jelent", u"[IGE][_IF=tA][PSe3][NOM]"), (u"jelent", u"[IGE][_MIB_SUBJ=tA][NOM]"), (u"jelentett", u"[FN][PSe3][NOM]"), (u"jelentet", u"[IGE][TMe3]"), (u"jelentet", u"[IGE][_IF=tA][PSe3][NOM]")],
                        u"jelentős": [(u"jelentős", u"[MN][NOM]"), (u"jelentős", u"[FN][NOM]")],
                        u"jelent": [(u"jelenik", u"[IGE][Me3]"), (u"jelen", u"[FN][ACC]"), (u"jelenik", u"[IGE][_MIB][NOM]"), (u"jelen", u"[MN][ACC]"), (u"jelent", u"[IGE][e3]")],
                        u"Jeszenszky": [(u"Jeszenszky", u"[FN][NOM]")],
                        u"jogérvényesülésért": [(u"jogérvényesülés", u"[FN][CAU]")],
                        u"jogokért": [(u"jog", u"[FN][PL][CAU]")],
                        u"jogosult": [(u"jogosul", u"[IGE][_MIB][NOM]"), (u"jogosult", u"[FN][NOM]"), (u"jogosult", u"[MN][NOM]"), (u"jogosul", u"[IGE][Me3]")],
                        u"jogszabályt": [(u"jogszabály", u"[FN][ACC]")],
                        u"jó": [(u"jó", u"[MN][NOM]"), (u"jó", u"[MSZ]"), (u"jó", u"[HA]")],
                        u"jön": [(u"jön", u"[IGE][e3]")],
                        u"jövevénynek": [(u"jövevény", u"[FN][DAT]")],
                        u"jövő": [(u"jövő", u"[MN][NOM]"), (u"jön", u"[IGE][_OKEP][NOM]"), (u"jő", u"[IGE][_OKEP][NOM]"), (u"jövő", u"[FN][NOM]")],
                        u"Jugoszlávia": [(u"Jugoszlávia", u"[FN][NOM]")],
                        u"július": [(u"július", u"[FN][NOM]")],
                        u"Kaliforniában": [(u"Kalifornia", u"[FN][INE]")],
                        u"kancellárja": [(u"kancellár", u"[FN][PSe3][NOM]")],
                        u"kapcsolatok": [(u"kapcsolat", u"[FN][PL][NOM]")],
                        u"kapcsolódó": [(u"kapcsolódik", u"[IGE][_OKEP][NOM]")],
                        u"Kara": [(u"kar", u"[FN][PSe3][NOM]"), (u"Kara", u"[FN][NOM]")],
                        u"károkat": [(u"kár", u"[FN][PL][ACC]")],
                        u"kártevője": [(u"kártevő", u"[FN][PSe3][NOM]"), (u"kártevő", u"[MN][PSe3][NOM]")],
                        u"katasztrófavédelmi": [(u"katasztrófavédelmi", u"[MN][NOM]")],
                        u"Katasztrófavédelmi": [(u"katasztrófavédelmi", u"[MN][NOM]")],
                        u"katonáinak": [(u"katona", u"[FN][PSe3i][DAT]")],
                        u"katonák": [(u"katona", u"[FN][PL][NOM]")],
                        u"kávét": [(u"kávé", u"[FN][ACC]")],
                        u"kb": [(u"kb", u"[FN][NOM]")],
                        u"kedvezni": [(u"kedvez", u"[IGE][INF]")],
                        u"kellemes": [(u"kellemes", u"[MN][NOM]")],
                        u"kellemetlen": [(u"kellemetlen", u"[MN][NOM]"), (u"kellemetlen", u"[MN][_ESSMOD=0]")],
                        u"kellene": [(u"kell", u"[IGE][Fe3]")],
                        u"kell": [(u"kell", u"[IGE][e3]")],
                        u"képviselők": [(u"képviselő", u"[MN][PL][NOM]"), (u"képvisel", u"[IGE][_OKEP][PL][NOM]"), (u"képviselő", u"[FN][PL][NOM]")],
                        u"képzés": [(u"képzés", u"[FN][NOM]")],
                        u"kérdés": [(u"kérdés", u"[FN][NOM]")],
                        u"kereskedők": [(u"kereskedő", u"[FN][PL][NOM]"), (u"kereskedik", u"[IGE][_OKEP][PL][NOM]")],
                        u"kéri": [(u"kér", u"[IGE][Te3]"), (u"kéri", u"[MN][NOM]")],
                        u"kerülő": [(u"kerülő", u"[FN][NOM]"), (u"kerül", u"[IGE][_OKEP][NOM]")],
                        u"kerültek": [(u"kerül", u"[IGE][_MIB][PL][NOM]"), (u"kerül", u"[IGE][Mt3]")],
                        u"került": [(u"kerül", u"[IGE][Me3]"), (u"kerül", u"[IGE][_MIB][NOM]")],
                        u"későbbi": [(u"késői", u"[MN][_FOK][NOM]"), (u"későbbi", u"[MN][NOM]")],
                        u"Később": [(u"később", u"[HA]"), (u"késő", u"[MN][_FOK][NOM]"), (u"késik", u"[IGE][_OKEP][_FOK][NOM]"), (u"későn", u"[HA][_FOK]")],
                        u"későn": [(u"késik", u"[IGE][_OKEP][_ESSMOD]"), (u"későn", u"[HA]"), (u"késő", u"[MN][_ESSMOD]"), (u"késő", u"[MN][SUP]"), (u"késik", u"[IGE][_OKEP][SUP]")],
                        u"készítenek": [(u"készít", u"[IGE][t3]")],
                        u"készít": [(u"készít", u"[IGE][e3]")],
                        u"Keszthelyi": [(u"Keszthelyi", u"[FN][NOM]"), (u"keszthelyi", u"[MN][NOM]")],
                        u"készülhet": [(u"készül", u"[IGE][_HAT][e3]")],
                        u"készülő": [(u"készül", u"[IGE][_OKEP][NOM]"), (u"készülő", u"[FN][NOM]")],
                        u"Kétéves": [(u"kétéves", u"[MN][NOM]"), (u"kétéves", u"[FN][NOM]")],
                        u"kétnapos": [(u"kétnapos", u"[FN][NOM]"), (u"kétnapos", u"[MN][NOM]")],
                        u"két": [(u"két", u"[SZN][NOM]")],
                        u"kezdhetnek": [(u"kezd", u"[IGE][_HAT][t3]")],
                        u"kezdtek": [(u"kezd", u"[IGE][Mt3]"), (u"kezd", u"[IGE][t2]")],
                        u"kezd": [(u"kezd", u"[IGE][e3]")],
                        u"kg": [(u"kg", u"[FN][NOM]")],
                        u"kihajtanak": [(u"kihajt", u"[IGE][t3]")],
                        u"kiirtották": [(u"kiirt", u"[IGE][TMt3]"), (u"kiirt", u"[IGE][_MIB_SUBJ=tA][PL][NOM]")],
                        u"kimetsszük": [(u"kimetsz", u"[IGE][Tt1]"), (u"kimetsz", u"[IGE][TPt1]")],
                        u"kincsei": [(u"kincs", u"[FN][PSe3i][NOM]")],
                        u"Kinyitottak": [(u"kinyit", u"[IGE][Mt3]"), (u"kinyit", u"[IGE][_MIB][PL][NOM]")],
                        u"király": [(u"király", u"[FN][NOM]")],
                        u"kirekesztésnek": [(u"kirekesztés", u"[FN][DAT]")],
                        u"Kis-Ázsia": [(u"Kis-Ázsia", u"[FN][NOM]"), (u"kis-Ázsia", u"[FN][NOM]")],
                        u"kis": [(u"kis", u"[MN][NOM]")],
                        u"kitűnő": [(u"kitűnő", u"[MN][NOM]"), (u"kitűnik", u"[IGE][_OKEP][NOM]")],
                        u"ki": [(u"ki", u"[IK]"), (u"ki", u"[FN|NM][NOM]")],
                        u"kiültetett": [(u"kiültet", u"[IGE][_MIB][NOM]"), (u"kiültet", u"[IGE][Me3]")],
                        u"kivágták": [(u"kivág", u"[IGE][TMt3]"), (u"kivág", u"[IGE][_MIB_SUBJ=tA][PL][NOM]")],
                        u"kivétel": [(u"kivétel", u"[FN][NOM]")],
                        u"klímájú": [(u"klímájú", u"[MN][NOM]")],
                        u"kockázatot": [(u"kockázat", u"[FN][ACC]")],
                        u"komoly": [(u"komoly", u"[MN][NOM]")],
                        u"korai": [(u"korai", u"[MN][NOM]"), (u"kor", u"[FN][PSe3i][NOM]")],
                        u"Korea": [(u"Korea", u"[FN][NOM]")],
                        u"kórházi": [(u"kórházi", u"[MN][NOM]")],
                        u"kormánytól": [(u"kormány", u"[FN][ABL]")],
                        u"kormány": [(u"kormány", u"[FN][NOM]")],
                        u"kormányzati": [(u"kormányzati", u"[MN][NOM]")],
                        u"koronája": [(u"korona", u"[FN][PSe3][NOM]")],
                        u"koronás": [(u"koronás", u"[MN][NOM]"), (u"koronás", u"[FN][NOM]")],
                        u"koszorúba": [(u"koszorú", u"[FN][ILL]")],
                        u"körülmények": [(u"körülmény", u"[FN][PL][NOM]")],
                        u"körül": [(u"körül", u"[IK]"), (u"körül", u"[NU]"), (u"kör", u"[FN][ESS]")],
                        u"kötöttek": [(u"köt", u"[IGE][Mt3]"), (u"köt", u"[IGE][_MIB][PL][NOM]"), (u"kötött", u"[MN][PL][NOM]")],
                        u"következőket": [(u"következő", u"[MN][PL][ACC]"), (u"következik", u"[IGE][_OKEP][PL][ACC]"), (u"következő", u"[FN][PL][ACC]")],
                        u"következő": [(u"következő", u"[MN][NOM]"), (u"következő", u"[FN][NOM]"), (u"következik", u"[IGE][_OKEP][NOM]")],
                        u"közéleti": [(u"közéleti", u"[MN][NOM]")],
                        u"Közeli": [(u"közeli", u"[MN][NOM]")],
                        u"közel": [(u"közel", u"[FN][NOM]"), (u"közel", u"[NU]"), (u"közel", u"[HA]")],
                        u"közepén": [(u"közép", u"[FN][PSe3][SUP]")],
                        u"középtávú": [(u"középtávú", u"[MN][NOM]")],
                        u"közét": [(u"köz", u"[FN][PSe3][ACC]"), (u"köz", u"[FN][POS][ACC]")],
                        u"közé": [(u"közé", u"[NU]"), (u"közé", u"[IK]"), (u"közé", u"[NU][e3]"), (u"köz", u"[FN][POS][NOM]")],
                        u"közigazgatási": [(u"közigazgatási", u"[MN][NOM]")],
                        u"közlekedőket!": [(u"közlekedik", u"[IGE][_OKEP][PL][ACC]")],
                        u"közleményében": [(u"közlemény", u"[FN][POS][INE]"), (u"közlemény", u"[FN][PSe3][INE]")],
                        u"közlése": [(u"közlés", u"[FN][PSe3][NOM]")],
                        u"közölte": [(u"közöl", u"[IGE][TMe3]"), (u"közöl", u"[IGE][_IF=tA][PSe3][NOM]"), (u"közöl", u"[IGE][_MIB_SUBJ=tA][NOM]")],
                        u"közösen": [(u"közös", u"[MN][_ESSMOD]")],
                        u"között": [(u"között", u"[NU]")],
                        u"közterületi": [(u"közterületi", u"[MN][NOM]")],
                        u"kukoricaszárral": [(u"kukoricaszár", u"[FN][INS]")],
                        u"kulcsa": [(u"kulcs", u"[FN][PSe3][NOM]")],
                        u"kultúrnövényeknek": [(u"kultúrnövény", u"[FN][PL][DAT]")],
                        u"kupacoljuk": [(u"kupacol", u"[FN][PSt3][NOM]")],
                        u"különben": [(u"különben", u"[HA]"), (u"különb", u"[MN][_ESSMOD]"), (u"külön", u"[MN][INE]")],
                        u"Különben": [(u"különben", u"[HA]"), (u"különb", u"[MN][_ESSMOD]"), (u"külön", u"[MN][INE]")],
                        u"különböző": [(u"különböző", u"[MN][NOM]"), (u"különbözik", u"[IGE][_OKEP][NOM]")],
                        u"különleges": [(u"különleges", u"[MN][NOM]")],
                        u"különös": [(u"különös", u"[MN][NOM]")],
                        u"lapinterjúban": [(u"lapinterjú", u"[FN][INE]")],
                        u"látszottak": [(u"látszik", u"[IGE][_MIB][PL][NOM]"), (u"látszik", u"[IGE][Mt3]")],
                        u"laza": [(u"laza", u"[MN][NOM]")],
                        u"leesik": [(u"leesik", u"[IGE][Tt3]"), (u"leesik", u"[IGE][e3]")],
                        u"lefagyás": [(u"lefagyás", u"[FN][NOM]")],
                        u"lefagynak": [(u"lefagy", u"[IGE][t3]")],
                        u"legbiztosabban": [(u"biztos", u"[FF][MN][_FOK][INE]"), (u"biztos", u"[FF][MN][_FOK][_ESSMOD]")],
                        u"legfőbb": [(u"fő", u"[FF][MN][_FOK][NOM]")],
                        u"leginkább": [(u"inkább", u"[FF][HA]"), (u"inka", u"[FF][MN][_FOK][NOM]")],
                        u"légiók": [(u"légió", u"[FN][PL][NOM]")],
                        u"legkiválóbb": [(u"kiváló", u"[FF][MN][_FOK][NOM]"), (u"kiválik", u"[FF][IGE][_OKEP][_FOK][NOM]")],
                        u"legöregebb": [(u"öreg", u"[FF][MN][_FOK][NOM]")],
                        u"legősibb": [(u"ősi", u"[FF][MN][_FOK][NOM]")],
                        u"legyen": [(u"van", u"[IGE][Pe3]"), (u"lesz", u"[IGE][Pe3]")],
                        u"lehetséges": [(u"lehetséges", u"[MN][NOM]")],
                        u"lehet": [(u"lesz", u"[IGE][_HAT][e3]"), (u"van", u"[IGE][_HAT][e3]")],
                        u"lehull": [(u"lehull", u"[IGE][e3]")],
                        u"lehúzott": [(u"lehúz", u"[IGE][Me3]"), (u"lehúz", u"[IGE][_MIB][NOM]")],
                        u"lejtőjén": [(u"lejtő", u"[FN][PSe3][SUP]"), (u"lejt", u"[IGE][_OKEP][PSe3][SUP]")],
                        u"lerúgja": [(u"lerúg", u"[IGE][TPe3]"), (u"lerúg", u"[IGE][Te3]")],
                        u"leszaggatják.": [(u"leszaggat", u"[IGE][Tt3]")],
                        u"leszedve": [(u"leszed", u"[IGE][_HIN]")],
                        u"lesznek": [(u"lesz", u"[IGE][t3]")],
                        u"lesz": [(u"lesz", u"[IGE][e3]")],
                        u"létesítenek": [(u"létesít", u"[IGE][t3]")],
                        u"létrehozott": [(u"létrehoz", u"[IGE][Me3]"), (u"létrehoz", u"[IGE][_MIB][NOM]")],
                        u"le": [(u"le", u"[IK]"), (u"le", u"[X]")],
                        u"Levelei": [(u"levél", u"[FN][PSe3i][NOM]")],
                        u"Levelet": [(u"levél", u"[FN][ACC]")],
                        u"levélhónaljában": [(u"levélhónalj", u"[FN][PSe3][INE]")],
                        u"lévő": [(u"lesz", u"[IGE][_OKEP][NOM]"), (u"van", u"[IGE][_OKEP][NOM]")],
                        u"levő": [(u"lesz", u"[IGE][_OKEP][NOM]"), (u"van", u"[IGE][_OKEP][NOM]"), (u"levő", u"[MN][NOM]")],
                        u"lila": [(u"lila", u"[MN][NOM]")],
                        u"lombfakadás": [(u"lombfakadás", u"[FN][NOM]")],
                        u"lombhullás": [(u"lombhullás", u"[FN][NOM]"), (u"lombhullás", u"[MN][NOM]")],
                        u"londoni": [(u"londoni", u"[MN][NOM]")],
                        u"Loránd": [(u"Loránd", u"[FN][NOM]")],
                        u"magas": [(u"magas", u"[MN][NOM]"), (u"magas", u"[FN][NOM]")],
                        u"mag": [(u"mag", u"[FN][NOM]")],
                        u"Magyar": [(u"Magyar", u"[FN][NOM]"), (u"magyar", u"[MN][NOM]")],
                        u"magyar": [(u"magyar", u"[MN][NOM]")],
                        u"majdnem": [(u"majdnem", u"[HA]")],
                        u"majd": [(u"majd", u"[HA]")],
                        u"május": [(u"május", u"[FN][NOM]")],
                        u"maradnak": [(u"marad", u"[IGE][t3]")],
                        u"marad": [(u"marad", u"[IGE][e3]")],
                        u"már": [(u"már", u"[HA]")],
                        u"második": [(u"második", u"[MN][NOM]")],
                        u"Más": [(u"más", u"[FN|NM][NOM]"), (u"más", u"[MN|NM][NOM]")],
                        u"matematikus": [(u"matematikus", u"[FN][NOM]")],
                        u"ma": [(u"ma", u"[HA]"), (u"ma", u"[FN][NOM]"), (u"ma", u"[FN][_TMP_INL]")],
                        u"médiaszabályozás": [(u"médiaszabályozás", u"[FN][NOM]")],
                        u"megfelelően": [(u"megfelelő", u"[MN][_ESSMOD]")],
                        u"meghálálja": [(u"meghálál", u"[IGE][TPe3]"), (u"meghálál", u"[IGE][Te3]")],
                        u"meghatározása": [(u"meghatározás", u"[FN][PSe3][NOM]")],
                        u"meghonosodásának": [(u"meghonosodás", u"[FN][PSe3][DAT]")],
                        u"meghúsosodik": [(u"meghúsosodik", u"[IGE][e3]")],
                        u"mégis": [(u"mégis", u"[HA]")],
                        u"megjelennek": [(u"megjelenik", u"[IGE][t3]")],
                        u"megkötésére": [(u"megkötés", u"[FN][POS][SUB]"), (u"megkötés", u"[FN][PSe3][SUB]")],
                        u"Megnő": [(u"megnő", u"[IGE][e3]")],
                        u"megőrlik": [(u"megőröl", u"[IGE][Tt3]")],
                        u"megporzásra": [(u"megporzás", u"[FN][SUB]")],
                        u"megpörkölik": [(u"megpörköl", u"[IGE][Tt3]")],
                        u"megritkítjuk": [(u"megritkít", u"[IGE][Tt1]")],
                        u"megtermékenyítés": [(u"megtermékenyítés", u"[FN][NOM]")],
                        u"Megtermékenyítés": [(u"megtermékenyítés", u"[FN][NOM]")],
                        u"megtesznek": [(u"megtesz", u"[IGE][t3]")],
                        u"még": [(u"még", u"[HA]")],
                        u"meg": [(u"meg", u"[IK]"), (u"meg", u"[KOT]")],
                        u"megyében": [(u"megye", u"[FN][INE]")],
                        u"megyére": [(u"megye", u"[FN][SUB]")],
                        u"megye": [(u"megye", u"[FN][NOM]")],
                        u"melegebb": [(u"meleg", u"[MN][_FOK][NOM]")],
                        u"meleg": [(u"meleg", u"[FN][NOM]"), (u"meleg", u"[MN][NOM]")],
                        u"mellett": [(u"mellett", u"[NU]")],
                        u"menti": [(u"ment", u"[IGE][Te3]"), (u"menti", u"[MN][NOM]")],
                        u"Mentőszervezetet": [(u"mentőszervezet", u"[FN][ACC]")],
                        u"mennyire": [(u"mennyi", u"[SZN|NM][SUB]"), (u"amennyire", u"[HA|NM]"), (u"amennyi", u"[SZN|NM][SUB]"), (u"mennyire", u"[HA|NM]")],
                        u"mérséklésének": [(u"mérséklés", u"[FN][POS][DAT]"), (u"mérséklés", u"[FN][PSe3][DAT]")],
                        u"mert": [(u"mert", u"[KOT]"), (u"mer", u"[IGE][Me3]"), (u"mer", u"[IGE][_MIB][NOM]")],
                        u"Meteorológiai": [(u"meteorológiai", u"[MN][NOM]")],
                        u"metsszük": [(u"metsz", u"[IGE][TPt1]"), (u"metsz", u"[IGE][Tt1]")],
                        u"mézédes": [(u"mézédes", u"[MN][NOM]"), (u"mézédes", u"[FN][NOM]")],
                        u"miatt": [(u"miatt", u"[NU]")],
                        u"Miklós": [(u"Miklós", u"[FN][NOM]")],
                        u"Mindenkinek": [(u"mindenki", u"[FN|NM][DAT]")],
                        u"mindent": [(u"minden", u"[FN|NM][ACC]")],
                        u"minden": [(u"minden", u"[DET]"), (u"minden", u"[FN|NM][NOM]"), (u"mind", u"[FN|NM][SUP]")],
                        u"mind": [(u"mind", u"[HA|NM]"), (u"mind", u"[FN|NM][NOM]"), (u"mind", u"[KOT]"), (u"mind", u"[HA]"), (u"mind", u"[DET]")],
                        u"minisztérium": [(u"minisztérium", u"[FN][NOM]")],
                        u"Minisztérium": [(u"minisztérium", u"[FN][NOM]")],
                        u"miniszter": [(u"miniszter", u"[FN][NOM]")],
                        u"mintha": [(u"mintha", u"[KOT]")],
                        u"mint": [(u"mint", u"[HA|NM]"), (u"mint", u"[KOT]"), (u"amint", u"[HA|NM]"), (u"mint", u"[PREP]")],
                        u"mi": [(u"mi", u"[FN|NM][NOM]"), (u"mi", u"[MN|NM][NOM]"), (u"ami", u"[DET|NM]"), (u"mi", u"[FN|NM][t1][NOM]")],
                        u"mondta": [(u"mond", u"[IGE][_MIB_SUBJ=tA][NOM]"), (u"mond", u"[IGE][TMe3]"), (u"mond", u"[IGE][_IF=tA][PSe3][NOM]")],
                        u"motiváció": [(u"motiváció", u"[FN][NOM]")],
                        u"MTI-hez": [(u"MTI", u"[FN][ALL]")],
                        u"MTI-nek": [(u"MTI", u"[FN][DAT]")],
                        u"MTI-vel": [(u"MTI", u"[FN][INS]")],
                        u"múlva": [(u"múl", u"[IGE][_HIN]"), (u"múlva", u"[NU]"), (u"múlik", u"[IGE][_HIN]")],
                        u"m": [(u"m", u"[FN][NOM]")],
                        u"mutatnak": [(u"mutat", u"[IGE][t3]")],
                        u"műsorában": [(u"műsor", u"[FN][PSe3][INE]")],
                        u"náddal": [(u"nád", u"[FN][INS]"), (u"náddal", u"[FN][NOM]")],
                        u"nagyobb": [(u"nagy", u"[MN][_FOK][NOM]")],
                        u"nagyok": [(u"nagy", u"[MN][PL][NOM]")],
                        u"Nagyon": [(u"nagyon", u"[HA]"), (u"Nagy", u"[FN][SUP]"), (u"nagy", u"[MN][SUP]")],
                        u"nagyon": [(u"nagyon", u"[HA]"), (u"nagy", u"[MN][SUP]")],
                        u"nagy": [(u"nagy", u"[MN][NOM]"), (u"nagy", u"[HA]")],
                        u"Nálunk": [(u"mi", u"[FN|NM][ADE][t1]")],
                        u"Napfényes": [(u"napfényes", u"[MN][NOM]"), (u"napfényes", u"[FN][NOM]")],
                        u"napig": [(u"nap", u"[FN][TER]")],
                        u"napokban": [(u"nap", u"[FN][PL][INE]")],
                        u"napos": [(u"napos", u"[MN][NOM]"), (u"napos", u"[FN][NOM]")],
                        u"napsütötte": [(u"napsütötte", u"[MN][NOM]")],
                        u"Navracsics": [(u"Navracsics", u"[FN][NOM]")],
                        u"néhány": [(u"néhány", u"[SZN][NOM]")],
                        u"nehezen": [(u"nehéz", u"[MN][_ESSMOD]")],
                        u"Nehezen": [(u"nehéz", u"[MN][_ESSMOD]")],
                        u"nehézséget": [(u"nehézség", u"[FN][ACC]")],
                        u"neki": [(u"neki", u"[IK]"), (u"ő", u"[FN|NM][DAT][e3]"), (u"neki", u"[HA]")],
                        u"nélküli": [(u"nélküli", u"[MN][NOM]")],
                        u"nélkül": [(u"nélkül", u"[NU]")],
                        u"német": [(u"német", u"[MN][NOM]")],
                        u"nem": [(u"nem", u"[HA]"), (u"nem", u"[FN][NOM]"), (u"nem", u"[MSZ]")],
                        u"nemzetbiztonsági": [(u"nemzetbiztonsági", u"[MN][NOM]")],
                        u"nemzetgazdasági": [(u"nemzetgazdasági", u"[MN][NOM]")],
                        u"népesítették": [(u"népesít", u"[IGE][TMt3]"), (u"népesít", u"[IGE][_MIB_SUBJ=tA][PL][NOM]")],
                        u"népes": [(u"népes", u"[MN][NOM]"), (u"népes", u"[FN][NOM]")],
                        u"néptáplálék": [(u"néptáplálék", u"[FN][NOM]")],
                        u"ne": [(u"ne", u"[ISZ]"), (u"ne", u"[HA]")],
                        u"nevel": [(u"nevel", u"[IGE][e3]")],
                        u"Neve": [(u"név", u"[FN][PSe3][NOM]")],
                        u"nevezték": [(u"nevez", u"[IGE][TMt3]"), (u"nevez", u"[IGE][_MIB_SUBJ=tA][PL][NOM]")],
                        u"néző": [(u"néző", u"[FN][NOM]"), (u"néz", u"[IGE][_OKEP][NOM]")],
                        u"nincs": [(u"nincs", u"[IGE][e3]")],
                        u"Nincs": [(u"nincs", u"[IGE][e3]")],
                        u"növekedni": [(u"növekszik", u"[IGE][INF]")],
                        u"növényeket": [(u"növény", u"[FN][PL][ACC]")],
                        u"növény": [(u"növény", u"[FN][NOM]")],
                        u"növényvédelemre": [(u"növényvédelem", u"[FN][SUB]")],
                        u"nyár": [(u"nyár", u"[FN][NOM]")],
                        u"nyilatkozatát": [(u"nyilatkozat", u"[FN][PSe3][ACC]")],
                        u"nyilatkozatot": [(u"nyilatkozat", u"[FN][ACC]")],
                        u"nyomtalanul": [(u"nyomtalan", u"[MN][_ESSMOD]")],
                        u"Nyrt.": [(u"nyrt.", u"[FN][NOM]")],
                        u"nyugati": [(u"nyugati", u"[MN][NOM]")],
                        u"okozta": [(u"okoz", u"[IGE][_IF=tA][PSe3][NOM]"), (u"okozta", u"[MN][NOM]"), (u"okoz", u"[IGE][TMe3]"), (u"okoz", u"[IGE][_MIB_SUBJ=tA][NOM]")],
                        u"okoz": [(u"okoz", u"[IGE][e3]")],
                        u"októberben": [(u"október", u"[FN][INE]")],
                        u"októberig": [(u"október", u"[FN][TER]")],
                        u"olajbogyó": [(u"olajbogyó", u"[FN][NOM]")],
                        u"olaszok": [(u"olasz", u"[MN][PL][NOM]")],
                        u"olasz": [(u"olasz", u"[MN][NOM]")],
                        u"olcsó": [(u"olcsó", u"[MN][NOM]")],
                        u"oldalakra": [(u"oldal", u"[FN][PL][SUB]")],
                        u"Ónos": [(u"ónos", u"[FN][NOM]"), (u"ónos", u"[MN][NOM]")],
                        u"Óriási": [(u"óriási", u"[MN][NOM]")],
                        u"országban": [(u"ország", u"[FN][INE]")],
                        u"országokból": [(u"ország", u"[FN][PL][ELA]")],
                        u"országos": [(u"országos", u"[MN][NOM]"), (u"országos", u"[FN][NOM]")],
                        u"Országos": [(u"országos", u"[MN][NOM]"), (u"országos", u"[FN][NOM]")],
                        u"Országgyűlés": [(u"országgyűlés", u"[FN][NOM]")],
                        u"Ószövetségben": [(u"ószövetség", u"[FN][INE]")],
                        u"osztanak": [(u"oszt", u"[IGE][t3]")],
                        u"óta": [(u"óta", u"[NU]")],
                        u"otthont": [(u"otthon", u"[FN][ACC]")],
                        u"öblösek": [(u"öblös", u"[MN][PL][NOM]")],
                        u"őket": [(u"ők", u"[FN|NM][t3][ACC]")],
                        u"Őket": [(u"ők", u"[FN|NM][t3][ACC]")],
                        u"öntözni": [(u"öntöz", u"[IGE][INF]")],
                        u"öntözzük": [(u"öntöz", u"[IGE][TPt1]"), (u"öntöz", u"[IGE][Tt1]")],
                        u"őrök": [(u"őr", u"[FN][PL][NOM]")],
                        u"ősrégi": [(u"ősrégi", u"[MN][NOM]")],
                        u"őszi": [(u"őszi", u"[MN][NOM]")],
                        u"ősz": [(u"ősz", u"[FN][NOM]"), (u"ősz", u"[MN][NOM]")],
                        u"Ötvenezer": [(u"ötvenezer", u"[SZN][NOM]")],
                        u"övezetet": [(u"övezet", u"[FN][ACC]")],
                        u"pálinka": [(u"pálinka", u"[FN][NOM]")],
                        u"pánik": [(u"pánik", u"[FN][NOM]"), (u"páni", u"[MN][PL][NOM]")],
                        u"párhuzamot": [(u"párhuzam", u"[FN][ACC]")],
                        u"parlament": [(u"parlament", u"[FN][NOM]")],
                        u"partjain": [(u"part", u"[FN][PSe3i][SUP]")],
                        u"partnerek": [(u"partner", u"[FN][PL][NOM]")],
                        u"Pécs": [(u"Pécs", u"[FN][NOM]")],
                        u"például": [(u"például", u"[HA]"), (u"példa", u"[FN][ESS]")],
                        u"pénzintézetek": [(u"pénzintézet", u"[FN][PL][NOM]")],
                        u"pénztárgépek": [(u"pénztárgép", u"[FN][PL][NOM]")],
                        u"Phenjan": [(u"Phenjan", u"[FN][NOM]")],
                        u"pirosas": [(u"pirosas", u"[FN][NOM]"), (u"pirosas", u"[MN][NOM]")],
                        u"polgárságért": [(u"polgárság", u"[FN][CAU]")],
                        u"politikusok": [(u"politikus", u"[FN][PL][NOM]")],
                        u"porbujtással": [(u"porbujtás", u"[FN][INS]")],
                        u"préselik": [(u"présel", u"[IGE][Tt3]")],
                        u"préselt": [(u"présel", u"[IGE][Me3]"), (u"présel", u"[IGE][_MIB][NOM]"), (u"préselt", u"[MN][NOM]")],
                        u"puha": [(u"puha", u"[MN][NOM]")],
                        u"pusztító": [(u"pusztít", u"[IGE][_OKEP][NOM]")],
                        u"rajtuk": [(u"ők", u"[FN|NM][SUP][t3]")],
                        u"rejlik": [(u"rejlik", u"[IGE][e3]"), (u"rejlik", u"[IGE][Tt3]")],
                        u"Remus": [(u"Remus", u"[FN][NOM]")],
                        u"rendkívüli": [(u"rendkívüli", u"[MN][NOM]")],
                        u"rendszeres": [(u"rendszeres", u"[FN][NOM]"), (u"rendszeres", u"[MN][NOM]")],
                        u"részarányos": [(u"részarányos", u"[MN][NOM]"), (u"részarányos", u"[FN][NOM]")],
                        u"részeket": [(u"rész", u"[FN][PL][ACC]")],
                        u"része": [(u"rész", u"[FN][PSe3][NOM]")],
                        u"révén": [(u"rév", u"[FN][PSe3][SUP]"), (u"révén", u"[NU][PSe3]"), (u"rév", u"[FN][POS][SUP]")],
                        u"rezsicsökkentéshez": [(u"rezsicsökkentés", u"[FN][ALL]")],
                        u"rezsicsökkentés": [(u"rezsicsökkentés", u"[FN][NOM]")],
                        u"rokona": [(u"rokon", u"[FN][PSe3][NOM]"), (u"rokon", u"[MN][PSe3][NOM]")],
                        u"róla": [(u"ő", u"[FN|NM][DEL][e3]")],
                        u"római": [(u"római", u"[MN][NOM]")],
                        u"Róma": [(u"Róma", u"[FN][NOM]")],
                        u"romlik": [(u"romlik", u"[IGE][e3]")],
                        u"Romulus": [(u"Romulus", u"[FN][NOM]")],
                        u"roppant": [(u"roppan", u"[IGE][Me3]"), (u"roppant", u"[HA]"), (u"roppant", u"[IGE][e3]"), (u"roppan", u"[IGE][_MIB][NOM]")],
                        u"rovar": [(u"rovar", u"[FN][NOM]")],
                        u"rügyek": [(u"rügy", u"[FN][PL][NOM]")],
                        u"Sajnos": [(u"sajnos", u"[HA]")],
                        u"sajtó": [(u"sajtó", u"[FN][NOM]")],
                        u"semmiféle": [(u"semmiféle", u"[MN][NOM]"), (u"semmiféle", u"[FN][NOM]")],
                        u"semmi": [(u"semmi", u"[FN][NOM]"), (u"semmi", u"[DET|NM]"), (u"semmi", u"[FN|NM][NOM]")],
                        u"sem": [(u"sem", u"[HA]"), (u"sem", u"[KOT]")],
                        u"senki": [(u"senki", u"[FN][NOM]"), (u"senki", u"[FN|NM][NOM]")],
                        u"serlegvirágzat": [(u"serlegvirágzat", u"[FN][NOM]")],
                        u"se": [(u"se", u"[HA]")],
                        u"simuló": [(u"simul", u"[IGE][_OKEP][NOM]"), (u"simuló", u"[MN][NOM]")],
                        u"Sir": [(u"sir", u"[FN][NOM]")],
                        u"sokfelé": [(u"sokfelé", u"[HA]")],
                        u"sokkal": [(u"sok", u"[SZN][INS]"), (u"sokk", u"[FN][INS]"), (u"sokkal", u"[HA]")],
                        u"sok": [(u"sok", u"[SZN][NOM]")],
                        u"Sok": [(u"sok", u"[SZN][NOM]")],
                        u"sorolja": [(u"sorol", u"[IGE][TPe3]"), (u"sorol", u"[IGE][Te3]")],
                        u"sor": [(u"sor", u"[FN][NOM]")],
                        u"sőt": [(u"sőt", u"[KOT]")],
                        u"sövényt": [(u"sövény", u"[FN][ACC]")],
                        u"Spanyolországban": [(u"Spanyolország", u"[FN][INE]")],
                        u"súlyos": [(u"súlyos", u"[MN][NOM]"), (u"súlyos", u"[FN][NOM]")],
                        u"sűrűn": [(u"sűrű", u"[MN][_ESSMOD]"), (u"sűrűn", u"[HA]"), (u"sűrű", u"[MN][SUP]")],
                        u"szabadon": [(u"szabad", u"[MN][_ESSMOD]"), (u"szabad", u"[FN][SUP]"), (u"szabad", u"[MN][SUP]")],
                        u"Szabadság-szoborhoz": [(u"szabadság-szobor", u"[FN][ALL]")],
                        u"szabad": [(u"szabad", u"[IGE][e3]"), (u"szabad", u"[MN][NOM]"), (u"szabad", u"[FN][NOM]")],
                        u"szabályok": [(u"szabály", u"[FN][PL][NOM]")],
                        u"szabályozásáról": [(u"szabályozás", u"[FN][PSe3][DEL]"), (u"szabályozásáról", u"[FN][NOM]")],
                        u"Szabolcsban": [(u"Szabolcs", u"[FN][INE]")],
                        u"Szabolcsot": [(u"Szabolcs", u"[FN][ACC]")],
                        u"Szabolcs-Szatmár-Bereg": [(u"Szabolcs-Szatmár-Bereg", u"[FN][NOM]")],
                        u"Szabolcs": [(u"Szabolcs", u"[FN][NOM]")],
                        u"Szakmaközi": [(u"szakmaközi", u"[MN][NOM]")],
                        u"szállítható": [(u"szállítható", u"[MN][NOM]")],
                        u"szálloda": [(u"szálloda", u"[FN][NOM]")],
                        u"szalmával": [(u"szalma", u"[FN][INS]")],
                        u"számítani": [(u"számít", u"[IGE][INF]")],
                        u"szaporítani": [(u"szaporít", u"[IGE][INF]")],
                        u"szaporítása": [(u"szaporítás", u"[FN][PSe3][NOM]")],
                        u"száraz": [(u"száraz", u"[IGE][e3]"), (u"száraz", u"[MN][NOM]")],
                        u"szárazságban": [(u"szárazság", u"[FN][INE]")],
                        u"szárított": [(u"szárít", u"[IGE][Me3]"), (u"szárít", u"[IGE][_MIB][NOM]"), (u"szárított", u"[MN][NOM]")],
                        u"származik": [(u"származik", u"[IGE][e3]")],
                        u"században": [(u"század", u"[SZN][INE]"), (u"század", u"[FN][INE]"), (u"száz", u"[SZN][PSe2][INE]")],
                        u"szélvédett": [(u"szélvédett", u"[MN][NOM]")],
                        u"Szemerédi": [(u"Szemerédi", u"[FN][NOM]"), (u"szemerédi", u"[MN][NOM]")],
                        u"szemétszállítási": [(u"szemétszállítási", u"[MN][NOM]")],
                        u"Szentendre": [(u"Szentendre", u"[FN][NOM]")],
                        u"szenvednek": [(u"szenved", u"[IGE][t3]")],
                        u"szerdai": [(u"szerdai", u"[MN][NOM]")],
                        u"szerda": [(u"szerda", u"[FN][NOM]")],
                        u"szerint": [(u"szerint", u"[NU]")],
                        u"Szerte": [(u"szerte", u"[IK]")],
                        u"Szervezet": [(u"szervezet", u"[FN][NOM]")],
                        u"szerzők": [(u"szerző", u"[FN][PL][NOM]"), (u"szerez", u"[IGE][_OKEP][PL][NOM]")],
                        u"szeszes": [(u"szeszes", u"[MN][NOM]"), (u"szeszes", u"[FN][NOM]")],
                        u"szétterülő": [(u"szétterül", u"[IGE][_OKEP][NOM]")],
                        u"szigetén": [(u"sziget", u"[FN][POS][SUP]"), (u"sziget", u"[FN][PSe3][SUP]")],
                        u"sziget": [(u"sziget", u"[FN][NOM]")],
                        u"szigorúbb": [(u"szigorú", u"[MN][_FOK][NOM]")],
                        u"sziklás": [(u"sziklás", u"[MN][NOM]"), (u"sziklás", u"[FN][NOM]")],
                        u"színéig": [(u"szín", u"[FN][POS][TER]"), (u"szín", u"[FN][PSe3][TER]")],
                        u"Szíria": [(u"Szíria", u"[FN][NOM]")],
                        u"szíves": [(u"szíves", u"[MN][NOM]"), (u"szíves", u"[FN][NOM]")],
                        u"szmirnai": [(u"szmirnai", u"[MN][NOM]")],
                        u"szobai": [(u"szobai", u"[MN][NOM]")],
                        u"szóbeli": [(u"szóbeli", u"[FN][NOM]"), (u"szóbeli", u"[MN][NOM]")],
                        u"szokták": [(u"szokik", u"[IGE][TMt3]"), (u"szokik", u"[IGE][_MIB_SUBJ=tA][PL][NOM]")],
                        u"Szolgálat": [(u"szolgálat", u"[FN][NOM]")],
                        u"szolgáltatási": [(u"szolgáltatási", u"[MN][NOM]")],
                        u"szopta": [(u"szopik", u"[IGE][TMe3]"), (u"szopik", u"[IGE][_IF=tA][PSe3][NOM]"), (u"szop", u"[IGE][TMe3]"), (u"szop", u"[IGE][_MIB_SUBJ=tA][NOM]"), (u"szop", u"[IGE][_IF=tA][PSe3][NOM]"), (u"szopik", u"[IGE][_MIB_SUBJ=tA][NOM]")],
                        u"szorul": [(u"szorul", u"[IGE][e3]")],
                        u"szó": [(u"szó", u"[FN][NOM]")],
                        u"szőlőket": [(u"szőlő", u"[FN][PL][ACC]")],
                        u"szőlő": [(u"szőlő", u"[FN][NOM]")],
                        u"Szöulban": [(u"Szöul", u"[FN][INE]")],
                        u"szükséges": [(u"szükséges", u"[MN][NOM]"), (u"szükséges", u"[FN][NOM]")],
                        u"szüretelhető": [(u"szüretelhető", u"[MN][NOM]")],
                        u"szüretével": [(u"szüret", u"[FN][PSe3][INS]"), (u"szüret", u"[FN][POS][INS]")],
                        u"tájain": [(u"táj", u"[FN][PSe3i][SUP]")],
                        u"takaratlan": [(u"takaratlan", u"[MN][NOM]"), (u"takaratlan", u"[MN][_ESSMOD=0]")],
                        u"talajban": [(u"talaj", u"[FN][INE]")],
                        u"talajokon": [(u"talaj", u"[FN][PL][SUP]")],
                        u"találhatjuk": [(u"talál", u"[IGE][_HAT][Tt1]")],
                        u"Tamás": [(u"Tamás", u"[FN][NOM]")],
                        u"támogatást": [(u"támogatás", u"[FN][ACC]")],
                        u"támogatja": [(u"támogat", u"[IGE][Te3]")],
                        u"tanárképzésben": [(u"tanárképzés", u"[FN][INE]")],
                        u"tanítsanak": [(u"tanít", u"[IGE][Pt3]")],
                        u"tantárgyat": [(u"tantárgy", u"[FN][ACC]")],
                        u"tápláló": [(u"táplál", u"[IGE][_OKEP][NOM]"), (u"tápláló", u"[MN][NOM]")],
                        u"tárgyalásával": [(u"tárgyalás", u"[FN][PSe3][INS]")],
                        u"tárgyalni": [(u"tárgyal", u"[IGE][INF]")],
                        u"tárgyal": [(u"tárgyal", u"[IGE][e3]")],
                        u"Tartós": [(u"tartós", u"[FN][NOM]"), (u"tartós", u"[MN][NOM]")],
                        u"Tavasszal": [(u"tavasz", u"[FN][INS]"), (u"tavasz", u"[FN][_TMP_INL]")],
                        u"tavaszán": [(u"tavasz", u"[FN][PSe3][SUP]")],
                        u"tavasz": [(u"tavasz", u"[FN][NOM]")],
                        u"tehát": [(u"tehát", u"[KOT]")],
                        u"tejét": [(u"tej", u"[FN][PSe3][ACC]"), (u"tej", u"[FN][POS][ACC]")],
                        u"tejnedvet": [(u"tejnedv", u"[FN][ACC]")],
                        u"teleinket": [(u"tél", u"[FN][PSt1i][ACC]")],
                        u"télen": [(u"tél", u"[FN][SUP]")],
                        u"telepítés": [(u"telepítés", u"[FN][NOM]")],
                        u"településen": [(u"település", u"[FN][SUP]")],
                        u"település": [(u"település", u"[FN][NOM]")],
                        u"télikabátot": [(u"télikabát", u"[FN][ACC]")],
                        u"teljesen": [(u"teljes", u"[MN][SUP]"), (u"teljes", u"[MN][_ESSMOD]")],
                        u"tél": [(u"tél", u"[FN][NOM]")],
                        u"teremnek": [(u"terem", u"[IGE][t3]"), (u"tér", u"[FN][PSe1][DAT]"), (u"terem", u"[FN][DAT]")],
                        u"teremni": [(u"terem", u"[IGE][INF]")],
                        u"terjedelmes": [(u"terjedelmes", u"[FN][NOM]"), (u"terjedelmes", u"[MN][NOM]")],
                        u"Terméktanács": [(u"terméktanács", u"[FN][NOM]")],
                        u"termelésével": [(u"termelés", u"[FN][POS][INS]"), (u"termelés", u"[FN][PSe3][INS]")],
                        u"termelik": [(u"termel", u"[IGE][Tt3]")],
                        u"termést": [(u"termés", u"[FN][ACC]")],
                        u"termés": [(u"termés", u"[FN][NOM]")],
                        u"természettudományi": [(u"természettudományi", u"[MN][NOM]")],
                        u"természettudományos": [(u"természettudományos", u"[FN][NOM]"), (u"természettudományos", u"[MN][NOM]")],
                        u"termeszteni": [(u"termeszt", u"[IGE][INF]")],
                        u"termesztőknek": [(u"termeszt", u"[IGE][_OKEP][PL][DAT]")],
                        u"termett": [(u"terem", u"[IGE][_MIB][NOM]"), (u"terem", u"[IGE][Me3]"), (u"termett", u"[MN][NOM]")],
                        u"termőhelyei": [(u"termőhely", u"[FN][PSe3i][NOM]")],
                        u"termőkorú": [(u"termőkorú", u"[MN][NOM]")],
                        u"terrorizmushoz": [(u"terrorizmus", u"[FN][ALL]")],
                        u"térségi": [(u"térségi", u"[MN][NOM]")],
                        u"területén": [(u"terület", u"[FN][PSe3][SUP]"), (u"terület", u"[FN][POS][SUP]")],
                        u"területére": [(u"terület", u"[FN][POS][SUB]"), (u"terület", u"[FN][PSe3][SUB]")],
                        u"területet": [(u"terület", u"[FN][ACC]")],
                        u"testrészek": [(u"testrész", u"[FN][PL][NOM]")],
                        u"Thomas": [(u"Thomas", u"[FN][NOM]")],
                        u"Tibor": [(u"Tibor", u"[FN][NOM]")],
                        u"Tihany": [(u"Tihany", u"[FN][NOM]")],
                        u"típusúak": [(u"típusú", u"[MN][PL][NOM]")],
                        u"típusú": [(u"típusú", u"[MN][NOM]")],
                        u"tíz": [(u"tíz", u"[SZN][NOM]")],
                        u"Tobin-ügy": [(u"Tobin-ügy", u"[FN][NOM]")],
                        u"továbbra": [(u"továbbra", u"[HA]")],
                        u"tovább": [(u"tovább", u"[HA]"), (u"tovább", u"[IK]")],
                        u"Többek": [(u"sok", u"[SZN][_FOK][PL][NOM]"), (u"sok", u"[FN|NM][_FOK][PL][NOM]")],
                        u"többen": [(u"sok", u"[SZN][_FOK][_ESSNUM]"), (u"sok", u"[SZN][_FOK][INE]"), (u"sok", u"[SZN][_FOK][_ESSMOD]")],
                        u"tőből": [(u"tő", u"[FN][ELA]")],
                        u"töltsük": [(u"tölt", u"[IGE][TPt1]")],
                        u"Tömegesebben": [(u"tömeges", u"[MN][_FOK][_ESSMOD]"), (u"tömeges", u"[MN][_FOK][SUP]"), (u"tömeges", u"[MN][_FOK][INE]")],
                        u"Törökországban": [(u"Törökország", u"[FN][INE]")],
                        u"törökök": [(u"török", u"[MN][PL][NOM]")],
                        u"történelemben": [(u"történelem", u"[FN][INE]")],
                        u"történt": [(u"történik", u"[IGE][_MIB][NOM]"), (u"történik", u"[IGE][Me3]")],
                        u"törvényi": [(u"törvényi", u"[MN][NOM]")],
                        u"törvényjavaslat": [(u"törvényjavaslat", u"[FN][NOM]")],
                        u"törvény": [(u"törvény", u"[FN][NOM]")],
                        u"törzse": [(u"törzs", u"[FN][PSe3][NOM]")],
                        u"trágyát": [(u"trágya", u"[FN][ACC]")],
                        u"Tudományegyetem": [(u"tudományegyetem", u"[FN][NOM]")],
                        u"tudós": [(u"tudós", u"[MN][NOM]"), (u"tudós", u"[FN][NOM]")],
                        u"túl": [(u"túl", u"[NU]"), (u"túl", u"[HA]"), (u"túl", u"[IK]")],
                        u"ugyancsak": [(u"ugyancsak", u"[HA]")],
                        u"újabb": [(u"új", u"[MN][_FOK][NOM]")],
                        u"Újabb": [(u"új", u"[MN][_FOK][NOM]")],
                        u"újjáépítését": [(u"újjáépítés", u"[FN][POS][ACC]"), (u"újjáépítés", u"[FN][PSe3][ACC]")],
                        u"újraegyesítési": [(u"újraegyesítési", u"[MN][NOM]")],
                        u"újraindítását": [(u"újraindítás", u"[FN][PSe3][ACC]")],
                        u"újra": [(u"újra", u"[IK]"), (u"újra", u"[HA]"), (u"új", u"[MN][SUB]")],
                        u"újságok": [(u"újság", u"[FN][PL][NOM]")],
                        u"új": [(u"új", u"[MN][NOM]")],
                        u"uniós": [(u"uniós", u"[FN][NOM]"), (u"uniós", u"[MN][NOM]")],
                        u"ún.": [(u"ún.", u"[MN][NOM]")],
                        u"uralkodása": [(u"uralkodás", u"[FN][PSe3][NOM]")],
                        u"utáni": [(u"utáni", u"[MN][NOM]")],
                        u"után": [(u"után", u"[NU]")],
                        u"út": [(u"út", u"[FN][NOM]")],
                        u"–": [(u"–", u"[HKJ]")],
                        u"`": [(u"`", u"[PUNCT]")],
                        u"=": [(u"=", u"[PUNCT]")],
                        u"-": [(u"-", u"[PUNCT]")],
                        u",": [(u",", u"[PUNCT]")],
                        u";": [(u";", u"[PUNCT]")],
                        u":": [(u":", u"[PUNCT]")],
                        u"!": [(u"!", u"[PUNCT]")],
                        u"?!": [(u"?!", u"[PUNCT]")],
                        u"?": [(u"?", u"[PUNCT]")],
                        u".........": [(u".........", u"[PUNCT]")],
                        u".......": [(u".......", u"[PUNCT]")],
                        u"......": [(u"......", u"[PUNCT]")],
                        u".....": [(u".....", u"[PUNCT]")],
                        u"....": [(u"....", u"[PUNCT]")],
                        u"...": [(u"...", u"[PUNCT]")],
                        u"..": [(u"..", u"[PUNCT]")],
                        u".": [(u".", u"[PUNCT]")],
                        u"·": [(u"·", u"[PUNCT]")],
                        u"'": [(u"'", u"[PUNCT]")],
                        u"\"": [(u"\"", u"[PUNCT]")],
                        u"«": [(u"«", u"[PUNCT]")],
                        u"»": [(u"»", u"[PUNCT]")],
                        u"(": [(u"(", u"[PUNCT]")],
                        u")": [(u")", u"[PUNCT]")],
                        u"[": [(u"[", u"[PUNCT]")],
                        u"]": [(u"]", u"[PUNCT]")],
                        u"&": [(u"&", u"[PUNCT]")],
                        u"+": [(u"+", u"[PUNCT]")],
                        u"→": [(u"→", u"[PUNCT]")],
                        u"•": [(u"•", u"[PUNCT]")],
                        u"—": [(u"—", u"[PUNCT]")],
                        u"…": [(u"…", u"[PUNCT]")],
                        u"ügyelni": [(u"ügyel", u"[IGE][INF]")],
                        u"ülésén": [(u"ülés", u"[FN][PSe3][SUP]"), (u"ülés", u"[FN][POS][SUP]")],
                        u"ültessünk": [(u"ültet", u"[IGE][Pt1]")],
                        u"ültetésű": [(u"ültetésű", u"[MN][NOM]")],
                        u"ültetett": [(u"ültet", u"[IGE][_MIB][NOM]"), (u"ültet", u"[IGE][Me3]")],
                        u"ültetni": [(u"ültet", u"[IGE][INF]")],
                        u"ültetvényeket": [(u"ültetvény", u"[FN][PL][ACC]")],
                        u"vadul": [(u"vadul", u"[IGE][e3]"), (u"vad", u"[MN][_ESSMOD]"), (u"vad", u"[FN][ESS]")],
                        u"vágjuk": [(u"vág", u"[IGE][TPt1]"), (u"vág", u"[IGE][Tt1]")],
                        u"vagy": [(u"van", u"[IGE][e2]"), (u"vagy", u"[KOT]"), (u"vagy", u"[HA]")],
                        u"valamint": [(u"valamint", u"[HA|NM]"), (u"valamint", u"[KOT]")],
                        u"vállalkozóknak": [(u"vállalkozó", u"[FN][PL][DAT]"), (u"vállalkozó", u"[MN][PL][DAT]"), (u"vállalkozik", u"[IGE][_OKEP][PL][DAT]")],
                        u"Valódi": [(u"valódi", u"[MN][NOM]")],
                        u"válogat": [(u"válogat", u"[IGE][e3]")],
                        u"valószínű": [(u"valószínű", u"[MN][NOM]")],
                        u"váltott": [(u"vált", u"[IGE][Me3]"), (u"vált", u"[IGE][_MIB][NOM]"), (u"váltott", u"[MN][NOM]")],
                        u"vannak": [(u"van", u"[IGE][t3]")],
                        u"van": [(u"van", u"[IGE][e3]")],
                        u"városalapítója": [(u"városalapító", u"[MN][PSe3][NOM]"), (u"városalapító", u"[FN][PSe3][NOM]")],
                        u"vasárnap": [(u"vasárnap", u"[FN][NOM]"), (u"vasárnap", u"[FN][_TMP_INL]"), (u"vasárnap", u"[HA]")],
                        u"védjék": [(u"véd", u"[IGE][TPt3]")],
                        u"végén": [(u"vég", u"[FN][POS][SUP]"), (u"vég", u"[FN][PSe3][SUP]")],
                        u"végre": [(u"vég", u"[FN][SUB]"), (u"végre", u"[IK]"), (u"végre", u"[HA]")],
                        u"végzi": [(u"végez", u"[IGE][Te3]")],
                        u"vegyék": [(u"vesz", u"[IGE][TPt3]")],
                        u"vegyük": [(u"vesz", u"[IGE][TPt1]")],
                        u"vélemények": [(u"vélemény", u"[FN][PL][NOM]")],
                        u"véli": [(u"vél", u"[IGE][Te3]")],
                        u"vendégnövénynek": [(u"vendégnövény", u"[FN][DAT]")],
                        u"versenyképes": [(u"versenyképes", u"[FN][NOM]"), (u"versenyképes", u"[MN][NOM]")],
                        u"vesszejéből": [(u"vessző", u"[FN][PSe3][ELA]")],
                        u"vesszőket": [(u"vessző", u"[FN][PL][ACC]")],
                        u"vesszőkön": [(u"vessző", u"[FN][PL][SUP]")],
                        u"vesszők": [(u"vessző", u"[FN][PL][NOM]")],
                        u"veszélyt": [(u"veszély", u"[FN][ACC]")],
                        u"veszély": [(u"veszély", u"[FN][NOM]")],
                        u"vezetője": [(u"vezető", u"[FN][PSe3][NOM]"), (u"vezet", u"[IGE][_OKEP][PSe3][NOM]")],
                        u"vidékeken": [(u"vidék", u"[FN][PL][SUP]")],
                        u"Virága": [(u"virág", u"[FN][PSe3][NOM]")],
                        u"virágja": [(u"virág", u"[FN][PSe3][NOM]")],
                        u"viseli": [(u"visel", u"[IGE][Te3]")],
                        u"viselő": [(u"viselő", u"[FN][NOM]"), (u"visel", u"[IGE][_OKEP][NOM]")],
                        u"visszafagynak": [(u"visszafagy", u"[IGE][t3]")],
                        u"visszametszeni": [(u"visszametsz", u"[IGE][INF]")],
                        u"visszavágjuk": [(u"visszavág", u"[IGE][Tt1]"), (u"visszavág", u"[IGE][TPt1]")],
                        u"viszont": [(u"viszont", u"[IK]"), (u"viszont", u"[KOT]")],
                        u"vitát": [(u"vita", u"[FN][ACC]")],
                        u"víz-": [(u"víz", u"[FN][NOM]")],
                        u"volna": [(u"volna", u"[IGE]"), (u"van", u"[IGE][Fe3]")],
                        u"voltak": [(u"van", u"[IGE][Mt3]"), (u"van", u"[IGE][_MIB][PL][NOM]"), (u"volt", u"[MN][PL][NOM]")],
                        u"volt": [(u"van", u"[IGE][Me3]"), (u"volt", u"[FN][NOM]"), (u"volt", u"[MN][NOM]"), (u"van", u"[IGE][_MIB][NOM]")],
                        u"vonatkoznának": [(u"vonatkozik", u"[IGE][Ft3]")],
                        u"vonta": [(u"von", u"[IGE][_MIB_SUBJ=tA][NOM]"), (u"von", u"[IGE][TMe3]"), (u"vonta", u"[MN][NOM]"), (u"von", u"[IGE][_IF=tA][PSe3][NOM]")],
                        u"vont": [(u"von", u"[IGE][_MIB][NOM]"), (u"von", u"[IGE][Me3]")],
                        u"Vonyarcvashegyen": [(u"Vonyarcvashegy", u"[FN][SUP]")],
                        u"zamatú": [(u"zamatú", u"[MN][NOM]")],
                        u"zárva": [(u"zárva", u"[HA]"), (u"zár", u"[IGE][_HIN]")],
                        u"zavarok": [(u"zavar", u"[FN][PL][NOM]"), (u"zavar", u"[IGE][e1]")],
                        u"Zöldség-Gyümölcs": [(u"zöldség-gyümölcs", u"[FN][NOM]"), (u"Zöldség-gyümölcs", u"[FN][NOM]")],
                        u"zöld": [(u"zöld", u"[MN][NOM]")],
                        u"zömök": [(u"zömök", u"[MN][NOM]"), (u"zöm", u"[FN][PL][NOM]")]
                  }


    # stem, csak a purePOS így hívja
    def analyze(self, word):
        if word in self.lexicon:
            return set(self.lexicon[word])
        else:
            return set()

if __name__ == "__main__":
    H = Humor()
    while True:
        INWORD = sys.stdin.readline()
        if not INWORD:
            break
        INWORD = INWORD.strip().decode("utf8")
        A = H.analyze(INWORD)
        if A:
            #OUT = "\t".join(map(lambda x: u"".join(x), a))
            OUT = "\t".join(map(lambda x: u"#".join([INWORD] + list(x)), A))
            print OUT.encode("utf8")
        else:
            print "UNK"
        sys.stdout.flush()
